vueComponent/ant-design-vue

- components/vc-table/src/TableHeaderRow.jsx
style被加到了attrs里面， 导致align对于表头不起效
> fix table header style

- components/list/index.en-US.md
- components/list/index.zh-CN.md
```rowKey``` is briefly mentioned in the Transfer component documentation, but it also is available on the List component. This property is very useful when you have to perform reordering operations on a list. The provided "index" slot scope does not work when you need to change the order of the items provided to the "dataSource" property, so the ability to define an alternate key for the items is necessary.
> Add documentation for "rowKey" property of List component

- docs/vue/customize-theme.en-US.md
- docs/vue/customize-theme.zh-CN.md
According to [the vue cli documentation](https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders) and my own try, it looks like that the solution proposed before gave an issue, or needed the user to install all loaders.
This solution, however, works like a charm out of the box!
You still have to load the `.less` file instead of `.css`, but that is described lower in the documentation.
> Change vue cli 3 way of customizing theme

- types/anchor/anchor.d.ts
- types/button/button.d.ts
- types/card.d.ts
- types/checkbox/checkbox.d.ts
- types/collapse/collapse.d.ts
- types/date-picker/date-picker.d.ts
- types/dropdown/dropdown.d.ts
- types/form/form.d.ts
- types/input/input.d.ts
- types/layout/layout-content.d.ts
- types/layout/layout-footer.d.ts
- types/layout/layout-header.d.ts
- types/layout/layout.d.ts
- types/list/list.d.ts
- types/menu/menu.d.ts
- types/radio/radio.d.ts
- types/select/select.d.ts
- types/steps/steps.d.ts
- types/table/table.d.ts
- types/tabs/tabs.d.ts
- types/tag/tag.d.ts
- types/timeline/timeline.d.ts
- types/tree-select.d.ts
- types/tree/tree.d.ts
ButtonGroup 应该是 Button 的静态属性。
RangePicker, MonthPicker, WeekPicker 也是 DatePicker 上的静态属性。
从组件的源码上看来，Layout上除了Sider子组件为静态属性外，还有Header, Content, Footer
然后在 class 中，propertyName: type 的意思是这个属性是什么类型，而不是是什么。所以加上了 typeof。
e.g.  without typeof，I coding
```javascript
Vue.component(Form.Item.name, Form.Item)
```
intellisense show Form.Item is a vue instance, not class，but expect is a class.
> fix: Button, DatePicker, Layout d.ts

- components/modal/ConfirmDialog.jsx
fix bug about modal method class inoperative
> fix bug about modal method class inoperative

- types/form/form.d.ts
> 3. Related issue link
fixes #526  …
> fix: update form validation typings #526

- docs/vue/use-with-vue-cli.zh-CN.md
初始化接入 `vue-cli3`
> 2. 要解决的问题。
运行 `npm run serve` 报错
> 3. 涉及UI/交互变动需要有截图或 GIF。
> 1. 英文描述
> 2. 中文描述（可选）
> 修改导致 vue-cli3 初始化运行 npm run serve 报错的文档。 

- components/vc-table/src/utils.js
> scroll measure not work fine on ff of win #579 
> 1. from https://github.com/react-component/table/commit/12335c2aab534eb8beaeb2223a90a35372b208dc#diff-2b4ca49d4bb0a774c4d4c1672d7aa781
>  fix scroll measure not work fine on ff of win
> 修正滚动条计算在 windows 下 firefox 无法正确计算的问题
windwos firefix bug:
```
// 有 overflow: 'scroll' 时，ff 下 offsetHeight  与 clientHeight 同高
size = scrollDiv.offsetHeight - scrollDiv.clientHeight; 
```
> fix: scroll measure not work fine on ff of win #579

- types/form/form.d.ts
修正 form  getFieldsError、getFieldsValue 方法参数为可选
> fix(typings): update form typings

- components/upload/Upload.jsx
- components/upload/index.en-US.md
- components/upload/index.zh-CN.md
- components/vc-upload/src/AjaxUploader.jsx
> 1. 拖拽文件到upload组件中，如果文件格式不匹配accept，需要给与用户一定的提示
> 1.  增加 reject event ，当文件格式不匹配时执行。
> 1. 不break 已有功能
> 1. 英文描述
add reject event for drag not accepted files to upload component
> 2. 中文描述（可选）
>
> add reject event for drag not accepted files to upload component

- components/modal/ConfirmDialog.jsx
- components/modal/index.en-US.md
- components/modal/index.zh-CN.md
- components/modal/style/confirm.less
For `Modal` component, when use it like [Modal.method()](https://vue.ant.design/components/modal/#Modal.method()), `close icon` will not display, but in practical, people may need a `close icon` for this dialog, so I made `closable` option for it, and default value is `false`.
As the background say, we can show `close icon` like below:
```js
Modal.info({
title: 'This is a …
```
> feat: add closable option for confirm dialog

- components/form/index.zh-CN.md
There is duplicate brace in the document of form.
> docs(form-cn): Remove duplicate brace

- components/dropdown/dropdown-button.jsx
I found the right button of the drop-down menu can still be clicked on by comparing it with the ant-react.
Fixed disabled state of dropdown menu with button.
> 3. GIF or snapshot …
> fix: dropdown button disable style

- components/form/FormItem.jsx
I want to use getFieldDecorator in jsx
FormItem render problem when use getFieldDecorator
https://github.com/vueComponent/ant-design-vue/issues/930
> 3. GIF or snapshot should be …
> fix issue #930

- components/upload/Upload.jsx
> 1. If combining Upload Component with Form Component,The Upload component will ocurr Error When running `form.resetFields()`. This is because that the code `form.resetFields()` will make `fileList` to `undefined` and Upload componenet watching `fileList` props to updatae `sFileList`.
> 3. Issue: https://github.com/vueComponent/ant-design-vue/issues/925
> fix: sFileList will be 'undefined' when run `form.resetFields()`

- types/table/column.d.ts
Table.Column
如果不设置成非必填 再使用的时候 必须包一层非必填的映射 不符合组件文档的说明
> 2. 要解决的问题。
每个字段都要填写
无
> 列表配置项改为全非必填

- components/dropdown/getDropdownProps.js
在某个列表上使用dropdown作为右键菜单弹出的菜单宽度与列表一样宽。
查看了vc-dropdown中有minOverlayWidthMatchTrigger属性可以控制。
ant-design-vue中现在无法设置这个属性，添加了这个属性。
```
<a-dropdown :minOverlayWidthMatchTrigger="false" :trigger="['contextmenu']">
....
</a-dropdown>
```
> dropdown添加minOverlayWidthMatchTrigger属性

- components/table/__tests__/Table.test.js
- components/table/__tests__/__snapshots__/Table.test.js.snap
- components/vc-table/src/TableCell.jsx
> 1. TableCell tdProps style overrided not extend when column set align
>  column[align] should not override custom cell style #973
>  修正 customCell 在使用 align 属性时，导致 style 被覆盖 #973 
> fix: column[align] should not override custom cell style #973

- components/tooltip/abstractTooltipProps.js
首先，感谢你的贡献！ 😄
新特性请提交至 feature 分支，其余可提交至 master 分支。
在一个维护者审核通过后合并。
请确保填写以下 pull request 的信息，谢谢！~
在使用popover过程中，发现不能更精细化的定制overlay的位置
> 2. 要解决的问题。
更精细的控制overlay的位置
[#1020 ]
因为popover是基于tooltip的，而tooltip内部已经支持[builtinPalcements属性](https://github.com/vueComponent/ant-design-vue/blob/7b3897305bbecefced568e3be0ed850e9807b8a4/components/tooltip/Tooltip.jsx#L64)，仅需要修改
`ant-design-vue/components/tooltip/abstractTooltipProps.js`文件，即可实现需求
a-popover(:builtinPlacements='customizedPlacements')
> 3. 涉及UI/交互变动需要有截图或 GIF。
无影响，因为tooltip的公开文档中并没有说明此方法
无
> 1. 英文描述
> 2. 中文描述（可选）
> add builtinPlacements prop in shared props

- components/vc-select/Select.jsx
when you pass `:value` to `<a-select>` as a `v-model` it doesn't work correctly and throws error on unmounting component.
> fixed issue on unmounting component

- components/tree-select/index.jsx
In merge commit 00f104757cef2441b9de39d10ba91e9bde762378, treeselect lose props treeData, it cause that treeNode.dataRef is undefined and treeselect can't dynamic load data.
> 3. …
> fix: treeNode dataRef is undefined

- types/upload.d.ts
> fix upload dragger

- components/select/index.en-US.md
- components/select/index.jsx
- components/select/index.zh-CN.md
- types/select/select.d.ts
用于指定多选时tag标签的最大文本长度，超出的文本会用...进行隐藏
> …
> feat: select add maxTagTextLength prop

- types/ant-design-vue.d.ts
- types/config-provider.d.ts
> Project build failed with `Module 'ant-design-vue/types' has no exported member 'ConfigProvider'` in Typescript.
> Add a definition.
> 1. Add ConfigProvider's TypeScript definition
> 2. 补充 ConfigProvider TypeScript 定义
> If …
> fix: no ConfigProvider's TypeScript definition

- components/input/Input.jsx
- components/input/__tests__/index.test.js
- components/input/style/index.less
- components/input/style/mixin.less
(1) clear icon在input disabled时不显示
(2) 修复allowClear图标样式，保持与后缀图标对齐（提前同步了部分样式，保证allowClear在当前版本的可用性）
#1296 
> 3. GIF or snapshot should be provided if includes UI/interactive …
> fix: input clear style

- components/menu/style/index.less
添加menu组件收起张开动画的卡顿现象。
> 1. English …
> 间距margin重置的bug

- types/statistic/statistic-countdown.d.ts
- types/statistic/statistic.d.ts
Remove typings error in the console when using ant-design-vue in my project. 
There is some inconsistancy in the typings of statistic-counted definition file, and that produce the following error during type checking:
`ant-design-vue/types/statistic/statistic-countdown"' has no default export.`
Should I create a separate issue ?
> fix: statistic countdown typings

- components/select/index.jsx
thank you for your contribution! 😄
https://codesandbox.io/s/vue-antd-template-765lf
> fix select`LabelInValue` validator PropsType 
> fix: select `labelInValue` validator prop type error

- components/table/style/index.less
当 table 有 border，title，并且columns左右有fixed，那thead应该是直角的。
> fix: table style

- components/tree/Tree.jsx
- components/tree/__tests__/__snapshots__/demo.test.js.snap
- components/tree/demo/index.vue
- components/tree/demo/replaceFields.md
- components/tree/index.en-US.md
- components/tree/index.zh-CN.md
- site/dev.js
- types/tree/tree.d.ts
首先，感谢你的贡献！ 😄
> 1. 替换treeNode中 title,key,children字段为treeData中对应的字段
> 1. 英文描述
> 2. 中文描述（可选）
> feat(tree): 添加form-props-'replaceFields'字段

- components/cascader/index.jsx
修复cascader组件在搜索时输入空格触发页面滚动的bug
#1427
> …
> fix: cascader input space bug

- types/ant-design-vue.d.ts
- types/empty.d.ts
The Empty component (added in 1.4.0) has no type def in the ant-design-vue project.
The Empty component had no typings definition and could not be imported independentely using the Typescript approach.
I didn't find any issue regarding this.
Added type definition for Empty component.
> fix: add typings for Empty component

- components/menu/index.en-US.md
- components/menu/index.zh-CN.md
Site / document update
Help to add `overflowedIndicator` parameter description.
the English & Chinese description is copied from the React version.
I have tested it and it works.
帮忙补充Menu的参数API说明.
中文、英文描述来自于React版本的说明.
有测试过可以作用, 且追查源码是存在其功能的.
source code: 
> ant-design-vue/components/vc-menu/Menu.jsx
> line 162
```
overflowedIndicator: getComponentFromProp(this, 'overflowedIndicator', props) || (
<span>···</span>
),
```
Doc is updated/provided
> Menu API Document Update

- components/table/index.en-US.md
- components/table/index.zh-CN.md
https://github.com/vueComponent/ant-design-vue/issues/1432
> docs(table): complement params

- components/vc-tabs/src/ScrollableTabBarNode.jsx
> ant-design-vue 1.4.8 or early `a-tabs` events `nextClick` not trigger
fix: tabs trigger `nextClick` event
修复 tabs 组件不触发 `nextClick` 事件
`Allow edits from maintainers`
> fix: tabs trigger nextClick event

- components/descriptions/__tests__/__snapshots__/demo.test.js.snap
- components/descriptions/demo/responsive.md
- components/descriptions/demo/size.md
- components/descriptions/demo/vertical-border.md
修复descriptions组件文档
> 2. What will say …
> fix: descriptions demo

- components/vc-table/src/TableCell.jsx
Need of creating grouping row when have slot customRender rule for column.
[Issue](https://github.com/vueComponent/ant-design-vue/issues/1487)
When using customRender method for table column and have slot customRender rule for …
> Push column argument to cell's customRender function call.

- components/vc-trigger/Trigger.jsx
首先，感谢你的贡献！ 😄
Trigger闭包内存泄漏问题
[https://github.com/vueComponent/ant-design-vue/issues/1482](https://github.com/vueComponent/ant-design-vue/issues/1482)
> 不使用闭包变量，使用一个组件内部的引用，每次渲染都会重新赋值
> 组件内部引用是否有其他风险？
> 1. fix: memory leak of Trigger
> 2. 修复: Trigger组件内存泄漏问题
> fix: memory leak of Trigger

- components/empty/style/index.less
外层的.ant-select-dropdown-menu-item样式设置了padding-right:@control-padding-horizontal + 20，得到padding的值为5px 32px 5px 12px，所以里层的.ant-empty-small的样式margin-left不需要加上@control-padding-horizontal
修复居中问题
> 2. List final API realization and …
> 修复select组件在mode为multiple或tags时，下拉选项为空时样式没有居中问题

- components/upload/UploadList.jsx
UploadList bug
get the picture base64 asynchronously, resulting in no rendering
> fix:picture is not rendered

- components/tree-select/interface.jsx
When value is number `TreeSelect` component will report type check failed warning . It should same as select.
> fix: [TreeSelect] type check failed when value is number

- components/carousel/index.en-US.md
- components/carousel/index.zh-CN.md
- components/table/index.en-US.md
- components/table/index.zh-CN.md
A: Custom Carousel styles.
> 2. What …
> carousel 新增参数 dotsClass 及文档优化

- components/statistic/Countdown.jsx
The `@finish` event in statistic countdown component doesn't work at all.
> fix: fix the "finish" event of statistic countdown

- build/config.js
- build/dev.js
- site/components/demoBox.vue
> 1. Import Primary component when only secondary component used in demo
> 3. Does this PR …
> perf: find parent component when only secondary component used in demo

- types/modal.d.ts
In https://github.com/vueComponent/ant-design-vue/commit/b8a0195379ea0862ae2464a68e92396c17e68604 the `parentContext` field was added to `ModalOptions`.
Since upgrading to 1.4.11 (which is the first release containing this change), I receive build errors in my TypeScript project on code like the following:
```ts
this.$error({ content: 'Error message goes here.' });
```
It produces a build error because the `parentContext` property is now required:
```
Error:(62, 21) TS2345: Argument of type '{ content: string; }' is not assignable to parameter of type 'ModalOptions'.
Property 'parentContext' is missing in type '{ content: string; }' but required in type 'ModalOptions'.
```
I don't think it was intentional that this property be required (if it was, that's a breaking change and should have …
> Make parentContext optional in ModalOptions type

- docs/vue/use-with-vue-cli.en-US.md
- [* ] Site / document update
English version document correction about its sample source files
Correct differences of sample source file in the document between Chinese and English version.
No issue link.
- [*] Doc is not needed
- [*] Demo is not needed
- [*] TypeScript definition is not needed
- [*] Changelog is not needed
> docs: update vue-cli of en-US, syncing with zh-CN

- components/vc-checkbox/src/Checkbox.jsx
The Spread syntax is only get own property of an object，but many properties of Event are on it's prototype chains, so the result is that the passed nativeEvent only has two property: isTrutsed  and shiftKey
#1810
> 2. List final …
> fix: nativeEvent is not a complete Event object

- components/index.js
- components/mentions/__test__/__snapshots__/demo.test.js.snap
- components/mentions/__test__/demo.test.js
- components/mentions/__test__/index.test.js
- components/mentions/demo/async.md
- components/mentions/demo/basic.md
- components/mentions/demo/form.md
- components/mentions/demo/index.vue
- components/mentions/demo/placement.md
- components/mentions/demo/prefix.md
- components/mentions/demo/readonly.md
- components/mentions/index.en-US.md
- components/mentions/index.jsx
- components/mentions/index.zh-CN.md
- components/mentions/style/index.js
- components/mentions/style/index.less
- components/style.js
- components/style/themes/default.less
- components/vc-mentions/index.js
- components/vc-mentions/src/DropdownMenu.jsx
- components/vc-mentions/src/KeywordTrigger.jsx
- components/vc-mentions/src/Mentions.jsx
- components/vc-mentions/src/Option.jsx
- components/vc-mentions/src/mentionsProps.js
- components/vc-mentions/src/placement.js
- components/vc-mentions/src/util.js
- site/components.js
- site/demo.js
- site/demoRoutes.js
- tests/__snapshots__/index.test.js.snap
> Feat Mentions

- types/ant-design-vue.d.ts
- types/mentions/mentions.d.ts
- types/mentions/option.d.ts
> Add Mentions Type

- components/mentions/index.jsx
移除从ConfigProvider里获取getPopupContainer参数，mentions组件不适用于公用的trigger.parentNode,使用了全局的getPopupContainer后会导致下拉菜单无法正常显示
> 3. GIF or snapshot should be provided if includes …
> fix: mentions getPopupCotainer value

- components/page-header/index.jsx
> 2. 由于项目需要动态判断是否有返回图标，但使用backIcon属性为false，并没有像api上说的能隐藏图标，查看代码后发现是“||” 判断的问题，导致设置为false后显示了默认值
> fix: page-header组件设置backIcon为false，隐藏backIcon失败问题

- components/input/ClearableLabeledInput.jsx
- components/input/Input.jsx
- components/input/Search.jsx
- components/input/inputProps.js
> fix: input search style bug #2077

- components/form-model/Form.jsx
- components/form-model/FormItem.jsx
- types/form-model/form.d.ts
首先，感谢你的贡献！ 😄
FormModel提供一种设置validate messages的方式
https://github.com/vueComponent/ant-design-vue/issues/2041
FormModel接受validateMessages属性，通过provide/inject传入FormModelItem的AsyncValidator。
无影响。
> 1. 英文描述
The FormModel component adds `validateMessages` property.
> 2. 中文描述（可选）
FormModel组件添加`validateMessages`属性。
> feat: form-model add validateMessages prop

- package.json
- webpack.config.js
Compile errors that occur when `less-loader` v6.0.0 is used
[#2180](https://github.com/vueComponent/ant-design-vue/pull/2180)
> 3. GIF or snapshot should be provided if includes …
> fix: compile error when updating less-loader to v6

- components/modal/style/modal.less
- components/style/themes/default.less
We're using antdv as our project's component library. I was looking to change to header split border's color when I realized the less variable was missing.
`@modal-footer-border-color-split` exists in this project and even `@modal-header-border-color-split` exists in antd of React library so I thought it makes sense that it also exists here. 
I haven't found any issues regarding this, and instead of opening one, I'm opening a PR that adds the variable to default.less and uses it in modal.less
This change allows the customization of modal component's header's split border's color to be customized separately from other split border colors.
Has no effect unless the variable is set to a different value in a custom theme. No breaking changes.
Resolves #2196 
Added …
> feat(style): add @modal-header-border-color-split variable

- components/cascader/style/index.less
icon disabled color 未生效
- EN：Fix Cascader menu icon color when disabled
- CN：修复 Cascader  选项图标禁用时的颜色
> style: fix cascader icon disabled color

- components/input/style/mixin.less
same as : https://github.com/ant-design/ant-design/issues/23984
- EN：Fix Select focus border style in Input.Group
- CN：修复 Input.Group 中 Select 选项 focus 边框样式
> style: fix select focused in input group

- components/table/Table.jsx
表格组件开启了分页，绑定在列上的 onFilter函数，在表格的分页组件进行渲染时，会多余调用N * 2次（分页组件实际只需要获得数据数组的大小，重新获取本地数据不必要）。 
当表格记录数越多，越影响性能。
> 1. Fix Table component‘s page subcomponent render performance.（Unnecessary getLocalData() call）
> 2. 优化表格开启分页时，自定义onFilter函数多次调用的问题
> 优化表格开启分页时，自定义onFilter函数多次调用的问题

- components/spin/Spin.jsx
- components/spin/index.js
- examples/index.js
> feat: update spin

- components/divider/index.jsx
- examples/index.js
> feat: update divider

- components/result/index.jsx
- examples/index.js
> feat: update result

- components/timeline/Timeline.jsx
- components/timeline/TimelineItem.jsx
- components/timeline/index.jsx
- examples/index.js
> feat: update timeline

- components/avatar/Avatar.jsx
- components/avatar/index.js
- examples/index.js
> feat: update avatar

- components/anchor/Anchor.jsx
- components/anchor/AnchorLink.jsx
- components/anchor/index.jsx
- examples/index.js
> feat: update anchor

- components/skeleton/index.jsx
- examples/index.js
> feat: update skeleton

- components/page-header/index.jsx
- examples/index.js
> feat: update pageheader

- components/descriptions/Col.jsx
- components/descriptions/index.jsx
> feat: update descriptions

- components/tag/CheckableTag.jsx
- components/tag/Tag.jsx
- components/tag/index.js
- examples/index.js
请注意有个破坏性更改，Tag使用时需要用 v-model:visible 不能使用 v-model 控制现隐。 CheckableTag 需要使用 v-model:checked 不能使用 v-model 控制是否被选中
> Feat Tag CheckableTag

- components/back-top/backTopTypes.js
- components/back-top/index.jsx
- examples/index.js
> feat: update BackTop

- components/radio/Group.jsx
- components/radio/Radio.jsx
- components/radio/RadioButton.jsx
- components/radio/index.js
- components/vc-checkbox/src/Checkbox.jsx
- examples/index.js
- package.json
- webpack.config.js
> feat: update radio

- breakChange-2.x.md
- components/_util/props-util.js
- components/steps/index.jsx
- components/vc-steps/Step.jsx
- components/vc-steps/Steps.jsx
- examples/index.js
> feat: update step

- components/upload/Upload.jsx
- components/upload/UploadList.jsx
- components/vc-progress/src/Circle.js
- components/vc-progress/src/Line.js
- components/vc-upload/src/AjaxUploader.jsx
- components/vc-upload/src/IframeUploader.jsx
- components/vc-upload/src/Upload.jsx
- examples/index.js
- webpack.config.js
> feat: update upload

- components/date-picker/interface.js
- components/date-picker/utils.js
- components/vc-calendar/src/Calendar.jsx
- components/vc-calendar/src/FullCalendar.jsx
- components/vc-calendar/src/Picker.jsx
- components/vc-calendar/src/RangeCalendar.jsx
- components/vc-calendar/src/date/DateInput.jsx
- components/vc-calendar/src/util/index.js
I'm trying to implement lunar calendar with datepicker, but obviously moment does not support the formatting of lunar calendar dates. It would be great to accept a function to render custom date strings in the input, instead of relying on moment.format().
DatePicker only allows momentjs formatting.
> 3. Related …
> feat: date picker custom format

- components/input/style/index.less
fix https://github.com/vueComponent/ant-design-vue/issues/2486
- 向下拖动正常
- 无法向上拖动
| # | Preview |
|---|---|
|Before ❌  | ![2020-07-07 16 03 25](https://user-images.githubusercontent.com/29775873/86743466-79758500-c06b-11ea-953e-641e5b3bde8f.gif)|
| After ✅ |  ![2020-07-07 16 04 32](https://user-images.githubusercontent.com/29775873/86743755-b3df2200-c06b-11ea-8776-cb4b57d7b9b2.gif) …
> fix: input textarea hadle when has affix

- components/list/Item.jsx
- components/list/__tests__/__snapshots__/empty.test.js.snap
- components/list/index.jsx
> feat(list): update to vue3

- components/grid/Col.jsx
- types/grid/col.d.ts
close https://github.com/vueComponent/ant-design-vue/issues/2558
```html
<a-row type="flex">
<a-col :flex="2">2 / 5</a-col>
<a-col :flex="3">3 / 5</a-col>
</a-row>
<a-row type="flex">
<a-col flex="100px">100px</a-col>
<a-col flex="auto">auto</a-col>
</a-row>
<a-row type="flex">
<a-col flex="1 1 200px">1 1 200px</a-col>
<a-col flex="0 1 300px">0 1 300px</a-col>
</a-row>
```
| | …
> feat: add col `flex`

- components/vc-pagination/Pagination.jsx
首先，感谢你的贡献！ 😄
希望在a-pagination的@change方法里直接使用双向绑定的current
> 2. 要解决的问题。
@change方法里得到的current的值是延后于双向绑定的时机的
对调change和change.current事件的先后顺序
一般不会有影响，除非之前的用户特意关注于这个先后顺序
> 1. 英文描述
> 2. 中文描述（可选）
> fix: [component:vc-pagination]emit change.current before change

- types/form-model/form.d.ts
首先，感谢你的贡献！ 😄
validate callback 返回类型错误
> 2. 要解决的问题。
validate callback 的第一个返回参数类型是 Boolean 对象，用这个值做 if 判断的时候，typescript 检查时会被认为永远是 true
无
> 1. 英文描述
> 2. 中文描述（可选）
> fix: validate callback return error type

- types/notification.d.ts
> chore: update type  notification

- types/modal.d.ts
> chore: update type modal

- .eslintignore
- types/layout/layout-content.d.ts
- types/layout/layout-footer.d.ts
- types/layout/layout-header.d.ts
- types/layout/layout-sider.d.ts
- types/layout/layout.d.ts
> chore(types): update Layout types

- types/slider.d.ts
- types/time-picker.d.ts
Update `Slider`, `TimePicker` typescript typo
> chore: update slider, time-picker typo

- components/menu/index.jsx
1. 重现地址：[antdv文档-Layout组件-侧边布局](https://2x.antdv.com/components/layout-cn/#%E4%BE%A7%E8%BE%B9%E5%B8%83%E5%B1%80)
2. 重现方式：菜单组件在展开二级菜单时，折叠Layout sider，子菜单无法跟随折叠.
3. 出现该问题是因为vue3中的 watch options 不再支持 key expressions 的方式使用 [vuejs/vue-next#2003]。因此导致 `Menu` 组件中无法 `watch` 到 `layoutSiderContext.sCollapsed`.
> fix: menu cannot be collapsed by the layout

- components/tree-select/index.jsx
-  Bug fix
> 1. issue link [https://github.com/vueComponent/ant-design-vue/issues/2826].
> 3. Does …
> fix bug tree select custom slot cann't use custom name

- types/input/input-search.d.ts
- types/input/input.d.ts
- types/input/password.d.ts
> fix(types): input prefix prop types

- components/table/Column.tsx
- components/table/Table.tsx
- components/table/index.tsx
- components/table/interface.ts
> chore: optimize table typescript support

- components/auto-complete/index.tsx
- components/badge/ScrollNumber.tsx
- components/cascader/index.tsx
- components/collapse/Collapse.tsx
- components/collapse/CollapsePanel.tsx
- components/drawer/index.tsx
- components/form/Form.tsx
- components/input/ResizableTextArea.tsx
- components/input/calculateNodeHeight.tsx
> fix: update components type

- components/message/index.tsx
修复message组件类型丢失
新版本切换到Typescript后发现多个版本未修复message类型被定义成any  工具无法进行方法联想
> fix: update message type

- components/button/button.tsx
> 1. 设置button组件loading属性值为{delay: 3000}无效
> 3. Does this PR contains potential break change or …
> fix: the button's loading property without delay

- components/menu/index.tsx
- components/tree/DirectoryTree.tsx
- components/tree/Tree.tsx
- components/tree/util.ts
这个tree组件花了挺长时间看的，之前没敢动因为缺失挺多类型的，然后发现了DirectoryTree.tsx文件中lastSelectedKey的默认值是空数组导致类型判断出了问题，在组件中其他位置用法都是string就默认给了个空字符串，这里做了一个小改动，然后添加了一些interface来给这几个组件做声明，字段是按文档给来声明的，如果有缺失或者错误的请指出~~
> fix: declare Tree Component type

- components/layout/layout.tsx
> Feat: Enhance Component Props Type

- components/radio/__tests__/group.test.js
- components/vc-checkbox/src/Checkbox.jsx
> fix: checkbox can't trigger change

- components/input/Password.tsx
- components/input/__tests__/index.test.js
> feat: input.password add iconRender

- components/affix/index.tsx
- components/affix/utils.ts
> refactor(affix): use Composition api

- components/radio/__tests__/group.test.js
- components/vc-checkbox/src/Checkbox.jsx
> fix: radio cancel change

- components/vc-slick/src/inner-slider.js
> 1. Use Carousel, set autoplay, autoplaySpeed, pauseOnDotsHover.
> 2. Hover on dots, it doesn't work.
> 1.  show file changes.
> 1. fix Carousel's prop of pauseOnDotsHover not work.
> 2. 修复Carousel组件pauseOnDotsHover失效问题。
> fix: carousel's pauseOnDotsHover not work

- components/popconfirm/__tests__/__snapshots__/index.test.js.snap
- components/popover/__tests__/__snapshots__/index.test.js.snap
- components/slider/__tests__/__snapshots__/index.test.js.snap
- components/tooltip/Tooltip.tsx
- components/tooltip/abstractTooltipProps.ts
- components/tooltip/style/index.less
- components/vc-tooltip/Content.jsx
- components/vc-tooltip/Tooltip.jsx
> feat: tooltip support color

- components/alert/index.tsx
> refactor(alert): use composition api

- components/alert/index.tsx
- components/alert/style/index.less
fix https://github.com/vueComponent/ant-design-vue/issues/3712
> fix: update alert style(#3712)

- components/badge/Badge.tsx
- components/badge/Ribbon.tsx
- components/badge/__tests__/index.test.js
- components/badge/index.ts
- components/badge/style/index.less
- components/badge/style/ribbon.less
- components/badge/utils.ts
> feat: add ribbon

- components/vc-select/generate.tsx
> fix: use window clearTimeout

- components/card/Card.jsx
- examples/App.vue
> 1. Set Card size with value 'small'.
> 2. Tabs in Card  should  has an prop to set.
> 3. https://github.com/vueComponent/ant-design-vue/issues/3741#issue-819907653
> 2. Chinese description …
> feat: add prop tab-size for card

- .gitignore
- antd-tools/generator-types/README.md
- antd-tools/generator-types/index.js
- antd-tools/generator-types/src/formatter.ts
- antd-tools/generator-types/src/index.ts
- antd-tools/generator-types/src/parser.ts
- antd-tools/generator-types/src/type.ts
- antd-tools/generator-types/src/utils.ts
- antd-tools/generator-types/src/vetur.ts
- antd-tools/generator-types/src/web-types.ts
- antd-tools/generator-types/tsconfig.json
- package.json
😄 **IDE support component properties Tips**
look this
```bash
npm run generator-webtypes
```
or
```bash
yarn generator-webtypes
```
> feat: add IDE types tips generator

- components/drawer/index.jsx
- components/vc-drawer/src/Drawer.js
> fix: drawer esc keydown

- components/back-top/index.jsx
ABackTop works abnormally under Keep-Alive
Need to support `activated` to handle `visible` of `BackTop`
> fix 'ABackTop visible issue under KeepAlive'

- components/vc-tree/src/TreeNode.jsx
`Tree` component's node's `class` prop doesn't work because of wrong usage of Vue template class syntax.
No matter what class name provided, it's always rendered as `className`.
> fix(tree): tree node class props invalid

- components/vc-checkbox/src/Checkbox.jsx
> fix: avoid emit update:checked twice

- antdv-demo/docs/table/demo/expand-children.md
- antdv-demo/docs/table/index.en-US.md
- antdv-demo/docs/table/index.zh-CN.md
- components/vc-table/src/ExpandableTable.jsx
It's same as event expandedRowsChange, but can be used with prop as `:expandedRowKeys.sync="expandedRowKeys"` for short.
Add the new event `update:expandedRowKeys`, and keep `expandedRowsChange` unchange for compatibility.
So we can use `:expandedRowKeys.sync="expandedRowKeys"`.
Find other props …
> feat: add event update:expandedRowKeys for Table

- antdv-demo/docs/table/demo/template.md
- antdv-demo/docs/table/index.en-US.md
- antdv-demo/docs/table/index.zh-CN.md
- components/table/index.jsx
Change the rule of translating template style API Table.Column to prop Table.columns. So that events @update:prop-abc and @prop-abc-change can be translated into prop onPropAbcChange in Table.columns, and we can use `:prop-abc.sync="abc"` in template style API.
Add event update:filterDropdownVisible for Table.Column
Add event update:filteredValue for Table.Column and add prop onFilteredValueChange for Table.columns
Change the rule of translating template style API Table.Column to prop Table.columns.
So that events @update:prop-abc and @prop-abc-change can be translated into prop onPropAbcChange in Table.columns,
We can use `:prop-abc.sync="abc"` in template style API.
> 1. Basic thought of …
> feat: add event update:filterDropdownVisible and update:filteredValue for Table.Column

- components/form/Form.tsx
> refactor(form): `scrollToFirstError` supports passing in options

- components/descriptions/index.tsx
首先，感谢你的贡献！ 😄
> 1. 要解决的问题。
当在tsx 中使用`Descriptions` 组件的column 属性时，如果只使用部分响应式属性，会出现下列提示，属性应为可选
```Type '{ xs: number; sm: number; }' is missing the following properties from type 'Record<Breakpoint, number>': md, lg, xxl, xl```
将`DEFAULT_COLUMN_MAP` 定义为`Partial<Record<Breakpoint, number>>` 可使生成的类型声明正常
> fix(descriptions): let breakpoint to be partial

- components/vc-virtual-list/List.tsx
> fix: virtual-list height reactive

- components/descriptions/index.tsx
> fix(descriptions): column prop number type error

- antdv-demo/docs/table/index.en-US.md
- antdv-demo/docs/table/index.zh-CN.md
If `Column.key` is ignored when using template style api, `Column.sorter` may fail.
Ref: #2501
> docs(table): require `Column.key` prop if using template style api

- antdv-demo/docs/form-model/index.en-US.md
- antdv-demo/docs/form-model/index.zh-CN.md
- components/form-model/Form.jsx
> 1. 目前 FormModel 属性 validateOnRuleChange 表现与文档不符，默认值应为false吧
> 2. What will …
> fix: set false as default value to validateOnRuleChange in FormModel

- components/avatar/Avatar.tsx
- components/avatar/__tests__/Avatar.test.js
- components/avatar/index.ts
> refactor(v3/avatar): refactor using composition api 

- components/vc-input-number/src/index.js
当input-number有焦点的时候，移除组件（unmount）时会首先触发blur事件，但是在blur里面使用了input框的ref，会导致报错。
既然用户已经移除了组件，肯定也不会希望收到blur事件。我觉得在ref为空时忽略掉blur事件就可以了
---
> fix(input-number): don't use `this.inputRef` when the component is already unmounted

- components/_util/props-util/index.js
- components/date-picker/createPicker.tsx
当 date-picker 中有注释节点时，date-picker不会显示，因为注释节点也可以作为一个 default slot,它会覆盖默认的input
```html
<a-date-picker>
</a-date-picker>
```
https://codesandbox.io/s/zen-nightingale-kwntz?file=/src/App.vue
判断下default …
> fix(date-picker): when default slot is a comment node, date-picker will not display

- components/list/Item.tsx
- components/list/contextKey.ts
- components/list/index.tsx
修复 #4263 
目前 `list/index.tsx` 引入了 `list/Item.tsx`，然后 `list/Item.tsx` 又引用了 `list/item.tsx`，出现了循环引用。
> fix(List): fix circular reference, which confuses vite (#4263)

- components/_util/hooks/useConfigInject.ts
- components/button/__tests__/__snapshots__/index.test.js.snap
- components/button/__tests__/index.test.js
- components/button/__tests__/wave.test.js
- components/button/button-group.tsx
- components/button/button.tsx
- components/button/buttonTypes.ts
- components/button/index.ts
- components/button/style/index.less
- components/button/style/mixin.less
- components/button/style/rtl.less
- components/date-picker/style/Calendar.less
- components/modal/ActionButton.tsx
- components/modal/Modal.tsx
- components/popconfirm/index.tsx
- components/style/themes/default.less
> refactor(3.x/button): use composition api

- components/switch/__tests__/index.test.js
- components/switch/index.tsx
> refactor(switch): support customize checked value #4329

- components/input/Password.jsx
> fix(input-password): accept global prefixCls

- components/tabs/style/index.less
card类型的tabs在切换选中时在windows系统上会导致tab移位
https://github.com/vueComponent/ant-design-vue/issues/4241
移除 .ant-tabs-nav .ant-tabs-tab-active中的font-weight:500。并加上text-shadow，以解决这个问题。
style(tabs): keep pace with antd(#4241)
> 1.x-fix#4241

- components/tabs/style/index.less
card类型的tabs在切换选中时在windows系统上会导致tab移位
https://github.com/vueComponent/ant-design-vue/issues/4241
移除 .ant-tabs-nav .ant-tabs-tab-active中的font-weight:500以解决这个问题且与antd的tabs保持一致
style(tabs): remove ant-tabs-tab-active's font-weight to keep pace with antd(#4241)
> style: keep pace with antd(#4241)

- components/table/Table.jsx
- components/table/index.jsx
> feat(table): support expandIcon slot

- components/icon/index.js
> fix(icon): ensure icon data is valid

- components/modal/Modal.tsx
- components/modal/__tests__/Modal.test.js
- components/modal/__tests__/__snapshots__/Modal.test.js.snap
`vc-dialog` 要求 `getContainer` 传入 `false` 来让弹窗渲染在当前dom里
https://github.com/vueComponent/ant-design-vue/blob/07f6d9edf0508a206dfdd7e4adc64049e7f7fbe0/components/vc-dialog/DialogWrap.jsx#L23
但是现在 `<a-modal>` 限制了 `getContainer` 只允许传入函数，导致用户无法指定弹窗在当前dom下显示，降低了灵活性。
然后在 `vc-dialog` 依赖的 [PortalWrapper](https://github.com/vueComponent/ant-design-vue/blob/next/components/_util/PortalWrapper.js#L61) 里还允许 `getContainer` 传入字符串
https://github.com/vueComponent/ant-design-vue/blob/07f6d9edf0508a206dfdd7e4adc64049e7f7fbe0/components/_util/PortalWrapper.js#L61
我也一并加上了
> fix(modal): allow Prop `getContainer` to be type of string & boolean

- components/vc-mentions/src/Mentions.jsx
首先，感谢你的贡献！ 😄
1. 我自己在使用过程中发现的问题，mentions 组件在输入中文或者日文字符时每次都会有吞字的现象出现
2. 解决在输入中文或者日文字符时吞字的问题
1. 我能想到的是两种解决方案。一种是在 onKeyUp 判断 event.target 的 composing 属性，如果是 true 证明当前正在输入中文或日文字符，这时不做处理直接返回。第二种就是在输入的过程中不去判断是否是中文或者日文字体。之前在 [#4520](https://github.com/vueComponent/ant-design-vue/pull/4520) 提交的是第二种方案，本次提交的是第一种。
> 1. 英文描述
> 2. 中文描述（可选）
> fix(mentions): chinese or japanese input error

- package.json
1. 今天在编译的时候一直在报 ts 文件编译的错误，后来试了几次发现应该是 4.4.0 以上版本的 breaking changes 影响了现有的代码，所以对 package.json 里面的 typescript 依赖版本做了限制，如果马上要对代码中 ts 的定义进行修复和升级的话就不用管这个 pr 了。
> fix: fix typescript version limit

- components/_util/props-util/initDefaultProps.ts
- components/vc-select/generate.tsx
> fix:  typescript compile error

- components/upload/interface.tsx
I tried to pass `method=patch` to the upload component, but it doesn't pass the check. The only supported methods are POST and PUT. This is unnecessary restrictive.
User can use RESTful API with the PATCH semantic
Support PATCH method in the upload component
Some very old browsers doesn't support the PATCH method at all …
> Support for patch method

- components/table/demo/ajax.vue
> docs(table): fix ajax demo

- components/form/useForm.ts
不知为何 TS 在这行把 `rulesRef` 判为非 undefined 了。实际上可能是 undefined，就导致 `Object.keys`抛出异常
> Fix(form): non-null predict for rulesRef

- components/form/useForm.ts
`useForm` 的 `{immediate: true}`不起作用，原因在于初次调用`modelFn`时， `names`总是为空。
> Fix(useForm): immdiate validate doesn't work

- components/modal/Modal.tsx
> When I'm using `Modal.confirm`, I found some typescript error report and I checked those type definition then I got `ModalFuncProps`.
> ![image](https://user-images.githubusercontent.com/46062972/133714384-186c02fd-8367-4a5c-ad23-93a6ef2833f5.png)
> 1. Basic thought of solution and …
> fix: ModalFuncProps types which can be string text

- components/vc-select/generate.tsx
```
<Select :value="myValue" @change="handleChange">
```
现象：在 `handleChange` 中修改`myValue`（一个 ref 对象）的值，Select 展示的当前值和`myValue`的实际值不一致。
解决方法：`mergedValue`应当仅受 props 上的 `value`控制
> fix(Select): mergedValue shouldn't modified by outValue

- antd-tools/gulpfile.js
- components/vc-progress/index.ts
- components/vc-progress/src/index.ts
- package.json
> feat: remove gulp-typescript

- components/transfer/__tests__/__snapshots__/demo.test.js.snap
- components/transfer/demo/advanced.vue
- components/transfer/demo/custom-item.vue
- components/transfer/demo/index.vue
- components/transfer/demo/oneway.vue
- components/transfer/demo/pagination.vue
- components/transfer/demo/search.vue
- components/transfer/demo/table-transfer.vue
- components/transfer/demo/tree-transfer.vue
- components/transfer/index.en-US.md
- components/transfer/index.tsx
- components/transfer/index.zh-CN.md
> refactor(transfer): docs & selectedKeys

- components/input/index.en-US.md
- components/input/index.zh-CN.md
close: #4826
> 1. Typos in document, see #4826 to get details.
> 2. Fix the typos.
> 3. Related issue: #4826.
> docs: fix typos in `Input`

- components/pagination/Pagination.tsx
Related issue: https://github.com/ant-design/ant-design/issues/25627
Explicitly tell crawlers not to crawl Paginattion <A> links that can't be crawled anyway
No other effect.
> fix: prevent Pagination <a> tag to be crawled

- package.json
- site/src/components/DemoBox.vue
- site/src/utils/generateOnlineDemo.ts
> doc: support CodeSandbox

- components/checkbox/index.en-US.md
- components/checkbox/index.zh-CN.md
The `value` prop of `Checkbox` component is missing in its document. it should be displayed in document.
> docs: complete missing prop of checkbox

- components/_util/responsiveObserve.ts
- components/grid/Col.tsx
- components/grid/Row.tsx
- components/grid/demo/responsive-more.vue
- components/grid/demo/responsive.vue
- components/grid/index.en-US.md
- components/grid/index.zh-CN.md
- components/grid/style/index.less
- components/layout/Sider.tsx
- components/layout/index.en-US.md
- components/layout/index.zh-CN.md
- components/list/demo/resposive.vue
- components/list/index.en-US.md
- components/list/index.tsx
- components/list/index.zh-CN.md
- components/style/themes/default.less
- components/table/index.en-US.md
- components/table/index.zh-CN.md
- site/src/components/header.jsx
- site/src/hooks/useMediaQuery.ts
- site/src/layouts/header/index.vue
- site/src/layouts/index.vue
> 1. support xxxl for large screen.
> 2. support xxxl for large screen ,now most screen is 4k & 5k even 6k，can make a different layout on large screen.
> 3. [Related issue link](https://github.com/vueComponent/ant-design-vue/issues/4952).
> feat: add xxxl grid col size for 4k&5k display

- components/slider/index.tsx
> fix Slider tipFormatter types

- components/carousel/demo/customArrows.vue
> 1. it is a spelling error in doc page
> 1. no effect to feature
> 1. fix zindex misspelled in customArrows.vue demo
> 2. 在跑马灯说明文档页面的demo中发现style部分代码的zindex拼写错误
> fix(carousel): zindex misspelled in customArrows.vue demo

- components/table/Table.tsx
- components/table/__tests__/__snapshots__/demo.test.js.snap
- components/table/demo/index.vue
- components/table/demo/responsive.vue
修复table设置responsive 无效的问题
> 2. What …
> fix(table): responsive invalid

- components/menu/index.en-US.md
- components/menu/index.zh-CN.md
> docs: update menu doc, add triggerSubMenuAction description

- components/progress/__tests__/__snapshots__/demo.test.js.snap
- components/progress/__tests__/__snapshots__/index.test.js.snap
- components/progress/progress.tsx
Fixes: https://github.com/vueComponent/ant-design-vue/issues/4929
- progress component `<span/>` had extraneous `title` attribute
- Fixes #4929
extraneous title not present, user won't see duplicate tooltip anymore
fix: remove extraneous title on progress
> fix: remove title on progress span #4929

- components/spin/index.zh-CN.md
- components/tabs/index.zh-CN.md
- components/upload/index.en-US.md
- components/upload/index.zh-CN.md
some markdown symbols in bold are written as ' ' in the document. Actually, it should be \` \`
> docs: fix document makdown display

- components/affix/index.tsx
- components/anchor/AnchorLink.tsx
- components/auto-complete/index.tsx
- components/badge/Ribbon.tsx
- components/breadcrumb/Breadcrumb.tsx
- components/breadcrumb/BreadcrumbItem.tsx
- components/breadcrumb/BreadcrumbSeparator.tsx
- components/button/buttonTypes.ts
- components/card/Card.tsx
- components/descriptions/index.tsx
- components/drawer/index.tsx
- components/grid/Col.tsx
- components/mentions/index.tsx
- components/menu/src/ItemGroup.tsx
- components/menu/src/MenuItem.tsx
- components/menu/src/SubMenu.tsx
- components/progress/Line.tsx
- components/progress/Steps.tsx
- components/radio/Group.tsx
- components/space/index.tsx
- components/switch/index.tsx
- components/tabs/src/TabNavList/OperationNode.tsx
- components/tabs/src/TabNavList/index.tsx
- components/tag/index.tsx
- components/time-picker/time-picker.tsx
- components/tree/DirectoryTree.tsx
- components/vc-align/Align.tsx
- components/vc-checkbox/Checkbox.tsx
首先，感谢你的贡献！ 😄
> 1. 由于业务需求，我需要对一些ant-design-vue的组件进行二次封装以增强组件功能，所以需要使用到ant-design-vue组件的props
> 1. 英文描述
> 2. 中文描述（可选）
> feat(components): export multiple components props

- components/vc-tree/utils/conductUtil.ts
> 1. 当多选树 为懒加载的时候 此时存在多选的默认值为未展开节点 控制台会抛出错误 虽然功能不存在问题 但是这样是不友好的 
> 2. 目前将警告降级从error到warning 期待更好的解决方案   
> …
> chore: Modify the warning in the conductutil file for attention

- components/form/Form.tsx
- components/form/interface.ts
> fix(FormItem): append a trigger field to the rule type

- components/input-number/index.en-US.md
- components/input-number/index.zh-CN.md
> fix(docs): [API] remove duplicate props

- components/cascader/index.en-US.md
- components/cascader/index.zh-CN.md
> docs(cascader): type definition

- components/tabs/__tests__/__snapshots__/demo.test.js.snap
- components/tabs/__tests__/__snapshots__/index.test.js.snap
- components/tabs/demo/position.vue
- components/tabs/index.en-US.md
- components/tabs/index.zh-CN.md
- components/tabs/src/Tabs.tsx
> fix(tabs): disabled animated when tabPosition is left/right

- components/layout/index.en-US.md
- components/layout/index.zh-CN.md
> docs(layout): update type definition

- components/image/index.en-US.md
- components/image/index.tsx
- components/image/index.zh-CN.md
- components/vc-image/src/Image.tsx
- components/vc-image/src/PreviewGroup.tsx
> fix(Image): can not cancel previewMask

- components/_util/reactivePick.ts
> 1. fix: [#5168](https://github.com/vueComponent/ant-design-vue/issues/5168)
> 1. use lodash fromPairs replace Object.fromEntries
> 1. we can run it in a development environment with earlier versions of browsers
> 1. fix: use fromPairs replace Object.fromEntries
> fix: use fromPairs replace Object.fromEntries

- components/vc-image/src/Preview.tsx
> feat: enable the left or right keyboard to switch image

- components/vc-picker/hooks/usePickerInput.ts
1. This is the original implementation in [`rc-picker`](https://github.com/react-component/picker/blob/master/src/hooks/usePickerInput.ts). it uses `useEffect` without any deps. Should we use `onMounted` directly in vue?
```tsx
useEffect(() =>
addGlobalMouseDownEvent((e: MouseEvent) => {
// ...
}),
);
```
2. let's see the current implementation. `globalMousedownEvent.value` is …
> fix(vc-picker): global `mousedown` handler in `usePickerInput` hooks is never registered

- components/tree/DirectoryTree.tsx
In `multiple` mode, on single click on tree node item, it should emit single value instead of multiple values.
See original implementation of `ant-design`: https://github.com/ant-design/ant-design/blob/8d05774053138e807755c616ba1cf3fa296200dd/components/tree/DirectoryTree.tsx#L160-L166
> fix(DirectoryTree): `selectedKeys` updating

- package.json
- scripts/commitizen.js
Hi, I am the author of `cz-git`, I have checked the commit message of the project, I think it can be help maintainers who use commitizen CLI.
github: https://github.com/Zhengqbbb/cz-git
website | guide: https://cz-git.qbenben.com
中文文档: https://cz-git.qbenben.com/zh/
- **Friendly**: …
> chore: use `czg` commitizen adapter

- components/vc-select/OptionList.tsx
- components/vc-virtual-list/hooks/useScrollTo.tsx
bug address(select no positioning): https://codesandbox.io/s/hardcore-mountain-pmfhl5?file=/src/App.vue
When I use the Select component，Automatic location is disabled when you discover that fieldNames is used
This is fixed to value，this is wrong，This will cause problems with passing fieldNames。
I'm done with the test，It's time to submit the code
thx
> 1. Does this PR affect user? …
> fix: select auto location

- components/typography/Base.tsx
- components/typography/demo/interactive.vue
Bug fix
typography 组件中copy按钮事件冒泡至整个文本，导致如果在文本上自定义点击响应时，触发重复的问题
function onCopyClick(e: MouseEvent) {
e.preventDefault();
e.stopPropagation();
}
onCopyClick中阻止事件冒泡
仅影响当前组件，无破坏性更新
> Detach copyable button action, no longer bubble to parent component #5746

- components/vc-image/src/PreviewGroup.tsx
> [Image - Ant Design Vue (antdv.com)](https://www.antdv.com/components/image#components-image-demo-preview-group-visible)
>
> A flash of pictures when previewing from one image was turned off [**Preview from one image**]
>
> 当使用相册模式预览的时候，在关闭预览的时候，会有一个一闪而过的图片（默认展示的图片）
> Fixed a flash of pictures when previewing was turned off ✨

- components/cascader/demo/index.vue
- components/cascader/demo/tagRender.vue
- components/cascader/index.tsx
- components/typography/__tests__/index.test.js
Cascader: Fix the tagRender option and add Demo :bug: :memo: …
> Cascader: Fix the tagRender option and add Demo :bug: :memo:

- components/avatar/index.en-US.md
- components/avatar/index.zh-CN.md
- components/badge/index.zh-CN.md
> fix(Badge) Change the description of the text attribute of the Badge component document

- components/config-provider/index.tsx
> 1. 自定义主题和自定义前缀无法同时使用
> 2. 经过排查，发现是因为在注册主题时，globalConfigForApi的prefixCls字段的值还没有更新
> fix: Cannot use custom prefixCls with custom theme color #6052

- components/tree/DirectoryTree.tsx
1. Describe the source of requirement.
Directory-tree's scrollTo method is missing.
2. Resolve what problem.
This PR is expose scrollTo method to fix the above problem.
3. Related issue link.
https://github.com/vueComponent/ant-design-vue/issues/6064
1. Basic thought of solution and other optional proposal.
Add scrollTo method in Directory-Tree setup expose.
2. List final API realization and usage sample.
Like documentation.
3. GIF or snapshot should be provided if includes UI/interactive modification.
None.
1. Does this PR affect user? Which part will be affected?
None.
2. What will say in changelog?
Fix the problem that Directory-tree's scrollTo method is missing.
3. Does this PR contains potential break change or other risk?
None
If this PR related with other PR or following info. You …
> fix(directory-tree): expose scrollTo method.

- components/tree/DirectoryTree.tsx
The previous PR don't pass lint.
The previous PR: https://github.com/vueComponent/ant-design-vue/pull/6067
The action of the previous PR: https://github.com/vueComponent/ant-design-vue/actions/runs/3358512217/jobs/5584252470
> style: fix lint code

- components/vc-notification/Notice.tsx
- Resolve what problem.
The mouseleave event of this component will create a timer after unmounted. So It may cause `onClose` event runs repeatedly.
- Related issue link.
fix #6144
使用 `notification` 的时候，它绑定了 `mouseLeave` 和 `mouseEnter` 事件。在我点击关闭按钮后，`unMounted` 事件运行后，又会运行 `mouseLeave`  事件，导致清除了定时器后又新建了一个定时器。所以会调用两次 `notification` 里 `onClose` 事件两次。
> fix[notification]: onClose event runs repeatedly

- components/_util/vnode.ts
- components/vc-slick/track.jsx
- components/vc-slick/utils/innerSliderUtils.js
首先，感谢你的贡献！ 😄
fix issue #6100 
> 分析：该问题的原因是 vue 中的 cloneVNode 方法在 clone 时未对 children 进行深度 clone；导致同一个 vnode 生成了两份 dom；从而导致该了问题。如下图所示：
> 解决方案：在原来的 cloneElement 基础上做了一层封装，对 vnode 做深度 clone。另因  _util/vnode.ts  的 cloneElement 方法存在大面积的使用，故将实现放在了  vc-slick/utils/innerSliderUtils.js 中
> 思考是否可以在 vue 中实现，是不是 vue 的 bug，有待进一步了解。
> 无
> 1. fix(vc-slick): Fix content responsiveness in carousel component slot. #6100
> 2. 修复轮播组件插槽中的内容响应。#6100
> fix(vc-slick): #6100 - Fix content responsiveness in carousel component slot.

- antd-tools/generator-types/index.js
- antd-tools/generator-types/src/formatter.ts
- antd-tools/generator-types/src/index.ts
- antd-tools/generator-types/src/parser.ts
- antd-tools/generator-types/src/type.ts
- antd-tools/generator-types/src/utils.ts
Hello everyone!
I want to contribute to the development of the project, I hope I'm not the only one who faces syntax highlighting problems when working in IDEA (WebStorm).
Not all tags and attributes are highlighted in Intellij IDEA and WebStorm IDEs. Some attributes are incorrectly filled in.
File generation (**vetur/attributes.json, vetur/tag.json, vetur/web-type.json**) is performed by parsing files **/components/*/index.en-US.md**
In this regard, there were several parsing errors that I fixed.
1. Duplication of tags in the **web-type.json** file, for example, `a-anchor`, `a-card` and many others. Different objects have different properties filled in somewhere events, somewhere attributes and somewhere slots.
Now they are all combined in a single object.
2. Some tags were incorrectly …
> fix(generator-types): Fixed some bugs (web-type.json)

- components/date-picker/index.en-US.md
- components/date-picker/index.zh-CN.md
> docs(date-picker): docs update

- components/vc-table/stickyScrollBar.tsx
> 1. 解决table组件中 `stickyScrollBar` 组件 `active` 态`className`被一直设置为激活的状态（未激活时也被设置了）
> none
> none
> fix: set the correct activce classname for stickyScrollBar

- components/form/demo/time-related-controls.vue
Add the `format` prop to the time-picker demo, which is used to format the display value of the time-picker.
I want to format the display of time-picker to `HH:mm`, but the [documentation](https://antdv.com/components/form#components-form-demo-time-related-controls) here only has `value-format` which was not reflected onto the UI.
Reference from AntDesign official docs: https://github.com/ant-design/ant-design/blob/master/components/time-picker/demo/hide-column.tsx
Avoid confusing developers because we don't know if there is a `format` prop that should be used to format the display value.
I don't know.
> Add "format" prop for time-picker demo

- components/_util/warning.ts
- components/anchor/Anchor.tsx
- components/config-provider/hooks/useConfigInject.ts
- components/divider/index.tsx
- components/dropdown/dropdown-button.tsx
- components/dropdown/dropdown.tsx
- components/grid/demo/flex-align.vue
- components/grid/demo/flex-order.vue
- components/grid/demo/flex-stretch.vue
- components/modal/Modal.tsx
- components/slider/index.tsx
- components/space/index.tsx
- components/tooltip/Tooltip.tsx
> fix: test case error

- components/vc-picker/panels/TimePanel/TimeBody.tsx
- [X ] Bug fix
Resolve the problem [The type of minute in porps disabledDateTime of DatePicker should be number, not a ComputedRef . #6231](https://github.com/vueComponent/ant-design-vue/issues/6231)
> fix: type of minute in props disabledDateTime of DatePicker

- components/input/ClearableLabeledInput.tsx
- components/input/Group.tsx
- components/input/Input.tsx
- components/input/TextArea.tsx
- components/input/style/index.tsx
- components/style.ts
> refactor:input

- components/select/index.en-US.md
- components/select/index.tsx
- components/select/index.zh-CN.md
- components/select/style/dropdown.tsx
- components/select/style/index.tsx
- components/select/style/multiple.tsx
- components/select/style/single.tsx
- components/select/utils/iconUtil.tsx
- components/style.ts
- components/theme/interface/components.ts
> refactor:select

- components/cascader/index.tsx
- components/drawer/index.tsx
- components/image/index.tsx
- components/page-header/index.tsx
- components/select/index.tsx
- components/tag/index.tsx
- components/tree-select/index.tsx
> fix: inject value maybe undefined && tag style invalid

- components/components.ts
- components/locale/en_US.ts
- components/locale/index.tsx
- components/locale/zh_CN.ts
- components/qrcode/__tests__/demo.test.js
- components/qrcode/demo/base.vue
- components/qrcode/demo/customColor.vue
- components/qrcode/demo/customSize.vue
- components/qrcode/demo/download.vue
- components/qrcode/demo/errorLevel.vue
- components/qrcode/demo/icon.vue
- components/qrcode/demo/index.vue
- components/qrcode/demo/popover.vue
- components/qrcode/demo/status.vue
- components/qrcode/index.en-US.md
- components/qrcode/index.tsx
- components/qrcode/index.zh-CN.md
- components/qrcode/interface.ts
- components/qrcode/style/index.ts
- components/theme/interface/components.ts
- package.json
- typings/global.d.ts
> feat: add qrcode

- components/upload/index.en-US.md
When I read en documentation for Upload component, I found there are two `directory` props in the API table. I checked `directory` prop in zh doc, it only has one. So I removed a `directory` prop row without 'Version 3.0'
> 3. GIF or snapshot should be provided if …
> docs(upload): remove duplicated prop `directory`

- site/src/theme/static/highlight.dark.less
- site/src/theme/static/index.less
> style: add dark style for `pre` and `code`

- components/upload/Upload.tsx
Hello!
I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues) of this repository and believe that this is not a duplicate.
**Version**
3.2.16
**Environment**
ant-design-vue 3.2.16; 
vue-3.2.0
**Reproduction link**
[https://codesandbox.io/s/a-upload-dragger-class-issue-nzg0v9?file=/src/App.vue](url)
**Steps to reproduce**
There is an incorrect rendering of the class "ant-upload-drag-container" in DOM. If we use an empty tag  `<a-upload-dragger></a-upload-dragger>`, the empty `<div>` with class` "[object Object]-drag-container"` renders in DOM. 
This happens because of an error in string 397 of the Upload.tsx file. 
`<div class={`${prefixCls}-drag-container`}>{slots.default?.()}</div>`
prefixCls - ComputedRef<string>, not a string.
To fix this issue, we can …
> fix: fix the bug with render class ant-upload-drag-container in dom

- components/_util/cssinjs/StyleContext.tsx
- components/_util/cssinjs/hooks/useGlobalCache.tsx
- components/_util/cssinjs/hooks/useStyleRegister.tsx
- components/_util/cssinjs/index.ts
- components/components.ts
- site/src/App.vue
- site/src/router/index.js
- site/src/vueDocs/compatible-style.en-US.md
- site/src/vueDocs/compatible-style.zh-CN.md
- typings/global.d.ts
增加 StyleProvider  处理 样式兼容 等问题
#6407 
```vue
<template>
<a-style-provider hash-priority="high">
<App/>
</a-style-provider>
</template>
```
> 3. GIF or snapshot should be provided …
> feat(StyleProvider): add StyleProvider handle cssinjs features

- components/progress/Circle.tsx
- components/progress/Line.tsx
- components/progress/Steps.tsx
- components/progress/__tests__/__snapshots__/demo.test.js.snap
- components/progress/__tests__/__snapshots__/index.test.js.snap
- components/progress/demo/circle-micro.vue
- components/progress/demo/circle-mini.vue
- components/progress/demo/index.vue
- components/progress/demo/size.vue
- components/progress/demo/steps.vue
- components/progress/index.en-US.md
- components/progress/index.zh-CN.md
- components/progress/progress.tsx
- components/progress/props.ts
- components/progress/utils.ts
- components/vc-progress/src/Circle.tsx
- components/vc-progress/src/types.ts
首先，感谢你的贡献！ 😄
增强 size 属性
deprecated width 属性
> 2. 要解决的问题。
增强 size 属性
deprecated width 属性
#6355
增加 getsize 函数 处理 以往兼容性问题
重构 size<= 20时触发变体
```vue
<template>
<div>
<a-progress
type="circle"
trail-color="#e6f4ff"
:percent="60"
:stroke-width="20"
:size="12"
:format="number => `进行中，已完成${number}%`"
/>
<span :style="{ marginLeft: 8 }">代码发布</span>
</div>
</template>
```
Progress 组件
```ts
if (process.env.NODE_ENV !== 'production') {
devWarning(
'successPercent' in props,
'Progress',
'`successPercent` is deprecated. Please use `success.percent` …
```
> refactor(Progress): enhance size prop and add variants

- components/vc-picker/RangePicker.tsx
计算属性 `mergedDisabled` 使用 `.value` 获取值
> fix(RangePicker): syntax errors

- site/src/router/index.js
- site/src/vueDocs/getting-started.en-US.md
- site/src/vueDocs/getting-started.zh-CN.md
- site/src/vueDocs/introduce.en-US.md
- site/src/vueDocs/introduce.zh-CN.md
- site/src/vueDocs/migration-v4.en-US.md
- site/src/vueDocs/migration-v4.zh-CN.md
site 缺少使用和升级文档
1. getting-started 更新
2. introduce 更新
3. migration-v4 新增
> Feat v4 vuedocs

- components/button/__tests__/index.test.js
- components/button/button.tsx
- components/button/index.en-US.md
- components/button/index.zh-CN.md
fix [#6483](https://github.com/vueComponent/ant-design-vue/issues/6483)
> Add focus and blur methods to buttons

- components/table/Table.tsx
- components/table/style/index.ts
- components/table/style/resize.ts
> fix table resizable && type error

- components/theme/internal.ts
处理切换主题的时候，暗黑主题不生效的问题 #6512 ，目前查看遇到的问题是`internal`下的`useToken`无法响应token，嵌套的`DesignTokenContext`拿到的是空，就导致了无法触发响应。
目前我用的解决方案是通过全局的属性进行桥接，不知道还有没有好一些的方案实现。
> fix: dealing with switching topics modal, notification, message does not take effect close #6512

- components/modal/Modal.tsx
- components/modal/__tests__/__snapshots__/demo.test.js.snap
- components/modal/confirm.tsx
- components/modal/demo/HookModal.vue
- components/modal/demo/index.vue
- components/modal/destroyFns.ts
- components/modal/index.en-US.md
- components/modal/index.tsx
- components/modal/index.zh-CN.md
- components/modal/useModal/HookModal.tsx
- components/modal/useModal/index.tsx
首先，感谢你的贡献！ 😄
解决modal 函数组件无法获取上下文而无法正确渲染
> 2. 要解决的问题。
解决modal 函数组件无法获取上下文而无法正确渲染
#6512
提供useModal hook
```vue
<template>
<div>
<a-button @click="showConfirm">Confirm</a-button>
<contextHolder />
</div>
</template>
<script lang="ts" setup>
import { Modal } from 'ant-design-vue';
import { ExclamationCircleOutlined } from '@ant-design/icons-vue';
import { createVNode } from 'vue';
const [modal, contextHolder] = Modal.useModal();
const showConfirm = () => {
modal.confirm({
title: 'Do you Want to delete these items?',
icon: createVNode(ExclamationCircleOutlined),
content: createVNode('div', { style: …
```
> feat(modal): add useModal

- components/button/__tests__/__snapshots__/demo.test.js.snap
- components/button/demo/basic.vue
- components/button/demo/block.vue
- components/button/demo/button-group.vue
- components/button/demo/danger.vue
- components/button/demo/disabled.vue
- components/button/demo/ghost.vue
- components/button/demo/icon.vue
- components/button/demo/loading.vue
- components/button/demo/multiple.vue
- components/button/demo/size.vue
> docs(button): update demo with space

- antd-tools/getBabelCommonConfig.js
按照文档和这个 babel 配置，[打包后的组件代码](https://www.npmjs.com/package/ant-design-vue?activeTab=code)应该是不需要转 es6 代码的，但是实际上是转换了
如果不配置 @babel/preset-env 的 targets ，就会使用 package.json 中 browserslist 字段，此时打包后的代码就是正确的（无需转换 es6 的代码）
参考 https://github.com/ant-design/antd-tools/blob/6d4722ad12e46148bbc1b0656072c1c3e4b5cdf8/lib/getBabelCommonConfig.js#L31
> chore: modify the babel configuration

- components/grid/index.en-US.md
- components/grid/index.zh-CN.md
同步ant-design官网grid文档 close #6544
> docs(grid): update grid docs

- components/layout/__tests__/__snapshots__/demo.test.js.snap
- components/layout/demo/basic.vue
- components/space/index.tsx
- components/steps/index.tsx
- components/switch/__tests__/__snapshots__/demo.test.js.snap
- components/switch/__tests__/index.test.js
- components/switch/demo/disabled.vue
- components/switch/demo/loading.vue
- components/switch/demo/size.vue
- components/switch/demo/text.vue
- site/src/components/antdv-token-previewer/component-demos/slider/sliderInBg.tsx
- site/src/components/antdv-token-previewer/component-demos/tag/tag.tsx
- site/src/components/antdv-token-previewer/overviews/Primary.tsx
- site/src/views/ComponentOverview.less
1. 修复layout组件 basic demo
2. 修复space组件 class style合并
3. 修复steps 内progressWidth在compact主题下样式
4. 修复文档overview，卡片hover动画
5. 更新switch组件demo
6. 修复themeeditor展示组件，行内样式缺少px
> fix components bug & update docs

- components/grid/demo/responsive.vue
- components/grid/index.en-US.md
- components/grid/index.zh-CN.md
- site/src/vueDocs/migration-v4.en-US.md
- site/src/vueDocs/migration-v4.zh-CN.md
我看着组件部分还有`xxxl`的属性，这一部分咱们还需要移除吗
> docs(grid): update migrate docs && delete xxxl in grid docs

- components/segmented/src/segmented.tsx
> First of all, thank you for your contribution! 😄
> 
> New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!
> 
> [[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
> 
> ### This is a ...
> * [ ]  New feature
> * [x]  Bug fix
> * [ ]  Site / document update
> * [ ]  Component style update
> * [ ]  TypeScript definition update
> * [ ]  Refactoring
> * [ ]  Code style optimization
> * [ ]  Branch merge
> * [ ]  Other (about what?)
> 
> ### What's the background?
> > 1. Describe the source of requirement. 
> > 2. Resolve what …
> fix: segmentd disabled label is undefined

- components/grid/Col.tsx
- components/grid/Row.tsx
- components/grid/demo/responsive-more.vue
- components/list/demo/resposive.vue
> fix(grid): remove grid xxxl attribute

- components/form/__tests__/__snapshots__/demo.test.js.snap
- components/form/demo/disabled.vue
- components/form/demo/index.vue
> docs(form): add form disabled demo

- components/tabs/src/TabNavList/OperationNode.tsx
fix issue [#6653](https://github.com/vueComponent/ant-design-vue/issues/6653)
**bug复现步骤**
1.打开 antdv 官网。定位到标签页。找到“自定义新增页签触发器”的示例。
2.一直点击“ADD”新增标签页，直到出现"..."。
3.点击“...”打开标签页弹窗，点击标签页的“X”关掉弹窗中所有的标签页，直到弹窗自动关闭。
4.再次添加几个新的标签页，这时标签页弹窗会自动打开。
**原因**
第3步，关掉所有的标签页，直到弹窗自动关闭后，控制Dropdown的visible还是true，没有重置为false
> fix(tabs):  the dropdown menu opened automatically in Customized trigger of new tab

- components/select/index.tsx
for boolean choices from backend, it's very common that `true` or `false` should be vaue type of select props
> feat: prop type of select should contain Boolean

- components/modal/style/index.ts
- components/vc-dialog/DialogWrap.tsx
- components/vc-drawer/src/DrawerWrapper.tsx
> fix(ScrollLocker): modal and drawer add autoLock prop with PortalWrapper

- components/empty/index.tsx
I tried using the image slot of the a-empty component according to the documentation and found that it didn't work, so I modified it
> fix(empty): Fix image slot failure issue

- components/upload/demo/upload-manually.vue
示例代码在运行时,ts类型报错.原因是试图在可能为 undefined 的对象上使用扩展运算符.
> :memo: 修改手动上传示例代码

- components/badge/Badge.tsx
- components/badge/style/index.ts
- components/float-button/FloatButton.tsx
- components/float-button/__tests__/__snapshots__/demo.test.js.snap
- components/float-button/demo/badge.vue
- components/float-button/demo/index.vue
- components/float-button/index.en-US.md
- components/float-button/index.zh-CN.md
- components/float-button/interface.ts
- components/float-button/style/index.ts
- components/float-button/util.ts
悬浮按钮添加徽标演示并修复徽标组件color属性不生效的问题
> docs: add badge demo & fix badge component color attribute invalid

- components/image/PreviewGroup.tsx
- components/vc-image/src/Preview.tsx
Added the functionality to preview images with horizontal and vertical flipping.
> 增加了预览图片水平以及竖直方向上翻转的功能
> feat(image): add image flip feature

- components/table/Table.tsx
fix: #6782 
```expandedRowRender``` is overwrited by ```slots.expandedRowRender```. if ```slots.expandedRowRender``` is undefined,  it won't render even if you add ```expandedRowRender``` prop on ```<a-table>```.
update ```expandedRowRender={slots.expandedRowRender}``` to  ```expandedRowRender={slots.expandedRowRender || props.expandedRowRender}``` can solve this problem.
> fix(table): expandedRowRender does't work(#6782)

- webpack.build.conf.js
1. 修复dayjs没有成功使用externals排除，导致dayjs在使用cdn方式加载时，日期时间组件的国际化受影响
> fix dayjs is not excluded in dist

- components/_util/cssinjs/hooks/useStyleRegister.tsx
- components/style/roundedArrow.ts
> feat: cssinjs add MULTI_VALUE key

- site/src/layouts/header/index.vue
顶部这个横幅的 background 和 text color，没有适配明暗模式
> docs: banner adjust light and dark mode

- README.md
- components/calendar/index.en-US.md
- components/cascader/index.en-US.md
- components/date-picker/index.en-US.md
- components/slider/index.en-US.md
- components/table/index.en-US.md
- components/tabs/index.en-US.md
- components/time-picker/index.en-US.md
- site/src/vueDocs/compatible-style.en-US.md
- site/src/vueDocs/introduce.en-US.md
一些中英文逗号，以及 .en-US.md 文件中直接使用了中文，没有翻译的问题
> chore: fix typo in en docs

- site/src/theme/static/dark.less
> docs: fix drawer-handler's background in dark mode

- site/src/layouts/PrevAndNext.vue
页面位于 docs 这个界面时，属性里面没有 subtitle，只有 enTitle 和 title。位于 componenets 界面时，属性里面又没有 enTitle，只有 subtitle 和 title。
| 界面 |  中文标题属性 |  英文标题属性 |
|  ----  | ----  | ----  |
| docs  | title | enTitle |
| componenets  | subtitle | title |
> docs: prev and next buttons only show cn title

- components/app/__tests__/__snapshots__/demo.test.js.snap
- components/app/__tests__/demo.test.js
- components/app/context.ts
- components/app/demo/basic.vue
- components/app/demo/index.vue
- components/app/demo/myPage.vue
- components/app/index.en-US.md
- components/app/index.tsx
- components/app/index.zh-CN.md
- components/app/style/index.ts
- components/components.ts
- components/theme/interface/components.ts
首先，感谢你的贡献！ 😄
> 2. 要解决的问题。
> 1. 英文描述
> 2. 中文描述（可选）
> feat(App): add App component

- components/tabs/src/TabNavList/OperationNode.tsx
- typings/global.d.ts
> fix(Tabs): dropdown show

- components/locale/zh_CN.ts
- components/modal/ConfirmDialog.tsx
> docs(Modal): confirm default oktext synch (#6745)

- components/input-number/index.tsx
fix input-number mouseup error  #6670
> fix(InputNumber): input-number mouseup

- README-zh_CN.md
- README.md
- site/src/components/Contributors/constants.ts
- site/src/components/Contributors/index.vue
- site/src/layouts/Demo.vue
> feat: add contributors list

- site/src/layouts/index.vue
- site/src/theme/static/common.less
- site/src/theme/static/toc.less
- site/src/views/ComponentOverview.less
- site/src/views/ComponentOverview.vue
1. 左边 sidebar 图片上面空着一块感觉不是很好看。右边的 affix 直接到 header 下面了。
after：
2. [ant-design/ant-design#40126](https://github.com/ant-design/ant-design/pull/40126)
> docs: improve site page

- components/tag/__tests__/__snapshots__/demo.test.js.snap
- components/tag/demo/border-less.vue
- components/tag/demo/checkable.vue
- components/tag/demo/index.vue
- components/tag/index.en-US.md
- components/tag/index.tsx
- components/tag/index.zh-CN.md
- components/tag/style/index.ts
> feat(Tag): add border less & synch checkable

- components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
- components/auto-complete/demo/allow-clear.vue
- components/auto-complete/demo/border-less.vue
- components/auto-complete/demo/index.vue
- components/auto-complete/index.en-US.md
- components/auto-complete/index.tsx
- components/auto-complete/index.zh-CN.md
> feat(AutoComplete): add border less and customize clear button

- components/config-provider/context.ts
fix: #6886 第二个示例
经过排查，发现 direction.value 是 undefined
> fix: default value for direction in configProvider

- site/src/layouts/header/Github.vue
1. optimized the background color under hover
2. gitHub icon support for tooltip hints
> docs: github icon support hover tips and optimized the background 

- components/modal/demo/fullscreen.vue
4.0.1
在官网关于`Modal`组件全屏的演示文档中，发现无法全屏显示Modal，如下图所示
> docs(Modal):fix full-screen modal on the presentation documentation has no effect🥠

- site/src/layouts/header/index.vue
- site/src/theme/static/responsive.less
> site: nav-phone-icon display normal

- components/table/Table.tsx
> fix: table expandColumnTitle slot type declaration

- components/image/PreviewGroup.tsx
4.0.1
`<ImageGroup/>`图片预览打开时候没有过渡动画
[ImageGroup without animation - CodeSandbox](https://codesandbox.io/s/imagegroup-without-animation-rc7mpp?file=/src/demo.vue)
1. 点击上述链接或者官网查看Image组件的文档
2. 点击ImageGroup的多个图片预览，没有过渡动画
> fix(ImageGroup):fix open imagegroup without animation 🍅

- components/transfer/style/index.tsx
> fix(transfer): checkbox click evt run repeatedly

- components/form/demo/dynamic-form-item.vue
并且这个判断有逻辑问题，当 `dynamicValidateForm.domains.length`  不为 1 的时候都被带上了 `disabled` 属性，并且 `disabled` 没有任何作用，依然可以点击。
> There is a logic issue here. When dynamicValidateForm.domains.length is not equal to 1, the component receives the disabled property. Furthermore, the disable property seems to serve no purpose, as you can also trigger a click event.
> docs: update dynamic form item demo

- components/list/demo/loadmore.vue
Corrects a single word which is probably taken from the React version.
> docs: correct simple copy-paste error

- components/_util/Portal.tsx
- components/config-provider/hooks/useConfigInject.ts
close: #6937 
1. In the `useConfigInject.ts` file, add `props.getContainer` to the return value of `getPopupContainer` so that we can correctly assign `getPopupContainer` in `useMessage.tsx`.
> 在  `useConfigInject.ts` 文件中将 `props.getContainer` 添加到 `getPopupContainer` 的返回中，这样我们才能正确的在 `useMessage.tsx` 中给 `getPopupContainer` 正确赋值
```diff
// useConfigInject.ts
const getPopupContainer = computed(
- () => props.getPopupContainer ?? configProvider.getPopupContainer?.value,
+ () => props.getContainer ?? props.getPopupContainer ?? configProvider.getPopupContainer?.value,
);
// useMessage.tsx
const { getPrefixCls, getPopupContainer } = useConfigInject('message', props);
```
2. Attempting to access the DOM elements of the page within the `onBeforeMount` lifecycle hook returns null. Therefore, this …
> fix(message): getContainer prop doesn't work

- components/vc-image/src/Image.tsx
close: #6944 
```diff
const [isShowPreview, setShowPreview] = useMergedState(!!previewVisible.value, {
value: previewVisible,
onChange: onPreviewVisibleChange,
});
- watch(isShowPreview, (val, preVal) => {
-  onPreviewVisibleChange(val, preVal);
- });
```
`useMergedState` 这个方法里面传递了 `onChange` 属性，所以就没有必要再监听 `isShowPreview` 的变化了
> fix(vc-image): remove repeat listener

- antd-tools/getWebpackConfig.js
- webpack.build.conf.js
> feat: provide esm output file in dist

- components/vc-upload/AjaxUploader.tsx
1. 修复 `<input type="file"/>`  在chrome117版本下，cancel事件冒泡 被外层 onCancel监听捕获的问题
上传组件弹出的文件选择框，点击取消后会一直冒泡传递到最外层。。这时候如果有个组件刚好写了onCancel就会被执行
> Fix Upload component event

- components/float-button/BackTop.tsx
[#7008 ](https://github.com/vueComponent/ant-design-vue/issues/7008)
将inheritAttrs删除是因为组件内有消费attrs，type从props中取则是被声明过的props无法从attribute中获取
> fix(FloatButton): BackTop attribute invalid

- components/select/demo/custom-dropdown-menu.vue
- components/vc-select/BaseSelect.tsx
[#6133 ](https://github.com/vueComponent/ant-design-vue/issues/6133)
> fix(Select): Dropdown box disappears when the input box gains focus

- components/_util/Portal.tsx
- components/message/useMessage.tsx
after #6942 has been merged, here are some problems for drawer. we must set container for `drawer` in `onBeforeMount` that make it render correctly.
> fix: setContainer in onBeforeMount for drawer

- components/menu/index.en-US.md
- components/menu/index.zh-CN.md
- components/menu/src/interface.ts
类型文件中字段`key`的类型为`Key`
```ts
// _util/type.ts line 22
export type Key = string | number;
```
> docs(menu): fix typo

- components/_util/cssinjs/StyleContext.tsx
> fix(StyleContext): fix style cache duplicate creation

- components/vc-picker/utils/getRanges.tsx
fix: #6911 ，正常情况已在 #6994 中解决。
fix: 另一种情况，当RangePick中同时存在getPopupContainer和showTime的时候还是会存在此问题。
> fix: rangePick onOk can't close the panel

- components/tag/demo/colorful.vue
> fix(tag): colorful demo css style

- components/_util/wave/index.tsx
- components/_util/wave/useWave.ts
- components/config-provider/context.ts
- components/config-provider/hooks/useConfigInject.ts
- components/config-provider/index.tsx
> feat(config-provider): wave config

- site/src/views/theme-editor/index.vue
close: #7035 
控制台输出
- 第一个输出是修改内容但没有出现错误的输出
- 第二个输出是制造了错误的输出
可以发现没有错误的时候 `status.contentErrors` 是 `null`, 出现错误时会有一个 `parseError` 字段。为什么不用 `isRepairable`  的原因是出现两个地方的错误时这个字段的值就会改变，如下图。
> fix(theme-editor): handleEditConfigChange logic

- components/watermark/index.tsx
the `color` variable of the watermark components  replace with `token.value.colorFill`， support dark theme.
> perf[watermark]: replace with token variable

- components/_util/vnode.ts
fix bug #7013 4.x版本同样有此问题，4.x与3.x版本源码一致，优先处理4.x，不知3.x是否也需要提pr？
3.x 版本代码如下：https://github.com/vueComponent/ant-design-vue/blob/3.x/components/_util/vnode.ts
出现此bug的原因
```ts
// 复现例子
export default defineComponent({
setup() {
const list = [{ title: "1-1" }, { title: "1-2" }];
return () => (
<Carousel>
{list.map((item) => (
<div key={item.title}>{item.title}</div>
))}
<div>
<h3>2</h3>
</div>
<div>
<h3>3</h3>
</div>
<div>
<h3>4</h3>
</div>
</Carousel>
);
}
});
```
```ts
// jsx渲染后的vnode结果如下
const vnode = {
type: "div", 
children: ["1-1"],//...
}
// deepCloneElement函数执行过程会把上述children同样当做vnode处理，被clone后返回一个空的vnode导致只有jsx出现渲染问题
export function deepCloneElement<T, U>(
vnode: VNode<T, U> | VNode<T, U>[],
nodeProps: NodeProps = {},
override = true,
mergeRef = false,
) {
if (Array.isArray(vnode)) { …
```
> fix(carousel): can not use jsx list map render children

- components/message/style/index.ts
Setting flex in the body property affects the fixed layout offset of the message.
Therefore the properties of the message's fixed layout are enhanced (e.g. `left` `transform`)
this is a mini reproduction [codeSandbox](https://codesandbox.io/s/vigorous-water-vw4qsq?file=/src/App.vue)
close #7065
> component(message): fix message offset error

- components/collapse/Collapse.tsx
> fix(collapse): custom prefix in animation

- components/_util/gapSize.ts
- components/_util/type.ts
- components/components.ts
- components/config-provider/context.ts
- components/flex/__testts__/__snapshots__/demo.test.js.snap
- components/flex/__testts__/demo.test.js
- components/flex/__testts__/index.test.js
- components/flex/demo/align.vue
- components/flex/demo/basic.vue
- components/flex/demo/combination.vue
- components/flex/demo/gap.vue
- components/flex/demo/index.vue
- components/flex/demo/wrap.vue
- components/flex/index.en-US.md
- components/flex/index.tsx
- components/flex/index.zh-CN.md
- components/flex/interface.ts
- components/flex/style/index.ts
- components/flex/utils.ts
- components/theme/interface/components.ts
synch antd 5.10.0 flex component
> feat(Flex): New component

- components/_util/hooks/_vueuse/_configurable.ts
- components/_util/hooks/_vueuse/is.ts
使用 Vite 5 打包时出现 Warning 提示 `/* #__PURE__*/` comment 被移除
相关文件 `components/_util/hooks/_vueuse/_configurable.ts`, `components/_util/hooks/_vueuse/is.ts`
相关 Issues: 
1. #7132
2. https://github.com/vitejs/vite/issues/15100#issuecomment-1835657597 
移除 `/* #__PURE__*/`
> fix: remove /* #__PURE__*/ comments

- plugin/md/markdownToVue.ts
Modify the official website code example, switch TS to JS, the top of the example should be '<script setup>'
> 【docs】：Code example 'setup' is missing

- components/notification/demo/hook.vue
中文文档里 Notification Hooks 调用描述中的变量名称有误，英文文档则正常。
> docs(notification): Fix hooks description in demo

- components/calendar/index.en-US.md
- components/calendar/index.zh-CN.md
Optimizing the layout of `note` in `calendar` component documents.
> docs(calendar): optimize calendar docs note layout

- site/src/layouts/header/index.less
In the current header component, only the switching version of the button has a highlighting effect on hover, while the other two buttons have no effect. In dark mode, standardizing the hover effect of all buttons can enhance user experience. This pr is to solve the problem of harmonizing the style of buttons under hover.
The expectation is as follows.
> docs(header): restore button hover style

- components/menu/index.en-US.md
- components/menu/index.zh-CN.md
In the current document, some anchor types of the menu do not scroll accurately when clicked. (e.g. `itemType[]`)
> docs(menu): repair anchor jump

- components/upload/Upload.tsx
- components/upload/index.en-US.md
- components/upload/index.zh-CN.md
> fix: Form disabled no effect on Upload

- components/vc-trigger/Popup/interface.ts
We have defined `onPopupAlign` function in `Tooltip` component.
```tsx
// components/tooltip/Tooltip.tsx
export default defineComponent({
setup() {
const onPopupAlign = (domNode: HTMLElement, align: any) => {};
const vcTooltipProps = {
onPopupAlign,
};
return wrapSSR(<VcTooltip {...vcTooltipProps}>{/* ... */}</VcTooltip>);
},
});
```
But this function will never invoked.
Because the props of `PopupInner` component do not accept `onAlign` prop. We need have to include it.
```diff
// components/vc-trigger/Popup/interface.ts
export const innerProps = {
// Align
+  onAlign: {
+    type: Function as PropType<(popupDomNode: HTMLElement, align: AlignType) => void>,
+  },
};
```
In this way, we can trigger this function from here:
```tsx
// components/vc-trigger/Popup/PopupInner.tsx
const …
```
> fix tooltip onPopupAlign never called

- components/typography/Base.tsx
1. 描述相关需求的来源。
切换tab时，typography内容有超出的节点会闪烁原文再显示省略
- typography组件包了一层ResizeObserver(内部)组件，这个组件使用了ResizeObserver(web)接口监听dom元素的resize改变的事件，当触发resize事件后，会调用dom元素的getBoundingClientRect方法获取dom元素的宽高，当宽高和之前不一致时会触发typography的文本重新计算事件。
- 而ResizeObserver(web)接口在dom元素脱离文档流时（比如自己或祖先节点设置display为none了）也会触发，此时dom元素的getBoundingClientRect返回的宽高皆为0，此时仍会触发typography的文本重新计算事件，而当被重新添加时，又会走一遍这个流程，所以在脱离文档流时的那一次计算，其实是多余的。
- 而上面说的闪烁的原因就在这一次多余的计算里产生的，在脱离文档流后执行重新计算时，因为用到了window.getComputedStyle去获取当前dom元素的样式属性，而当前dom元素已经脱离文档流了，所以相关的样式属性和实际是有偏离的，比如width属性，在dom元素处于文档流中时，它是有一个实际的值的，而脱离文档流之后dom元素的width属性在没有特别设置的情况下，就是默认值auto
- 在width是auto时，按ellipsis的计算逻辑，被计算的文本相当于没有宽度的限制，最终的高度只有一行，因此在inRange的判定下，得到的结果都是没有超出，不需要省略，于是就变成了原文展示。
所以当dom元素被重新添加到文档流后，就会先显示上一次的原文，然后等待ResizeObserver(web)接口的监听事件，再在nextFrame重新去执行typography的文本计算事件。这个 …
> fix(Typography): fast and efficient syncEllipsis

- components/menu/src/Menu.tsx
flx close #7148  close #https://github.com/vueComponent/ant-design-vue/pull/7150
> fix(Menu.SubMenu): Fixed the issue that animation transitions in SubMenu mode invalidated after setting the prefixCls property globally

- components/vc-picker/RangePicker.tsx
当我配置 open为false时，聚焦结束时间框时， 发现active状态仍是开始框， 而光标已经移入结束框， 如图（可能光标截取不到）：
我认为active应聚焦在结束时间框下， 所以对代码做了些改动。
> fix: dataRange active-bar

- components/_util/vnode.ts
- components/modal/confirm.tsx
In vue 3.4.x, the execution logic of the `update` function has been changed so that calling `update` directly does not update the component.
In this case, the logic for updating the component should be abstracted into a function (e.g. `triggerVNodeUpdate`), and any subsequent manual calls to `update` should be replaced with `triggerVNodeUpdate(instance)`.
close #7239
> fix(vue): fixed modal component failed to trigger update in vue@3.4.x

- components/_util/cssinjs/hooks/useCacheToken.tsx
nuxt generate when NODE_ENV is prerender。
If this pr is not available, the user needs to handle it manually, like this → [nuxt-antd-css-demo](https://github.com/markthree/nuxt-antd-css-demo/blob/main/modules/antd.ts#L16)。
> fix: fix css prefix in nuxt generate

- components/table/hooks/useFilter/FilterDropdown.tsx
- components/table/index.en-US.md
- components/table/index.zh-CN.md
- components/table/interface.tsx
1. 修正 `FilterDropdown.tsx` 里的拼写错误 🐶
2. 补全 `components/table/interface.tsx` 中 `FilterDropdownProps` 的 `clearFilters` 属性类型及对应文档
> fix(table): Supplement FilterDropdown type

- components/_util/__mocks__/RenderSlot.tsx
- components/_util/__tests__/vNode.test.js
- components/_util/vnode.ts
- components/card/Card.tsx
- components/vc-table/Cell/index.tsx
- components/vc-table/hooks/useColumns.tsx
replace vue's private `renderSlot` method with the `customRenderSlot` method.
what `customRenderSlot` does is enhance the way `jsx` is rendered, so that if there is only a `Comment` or `Fragment` in the `slot`, the default content is rendered, in line with what is expected from `template` rendering.
close #7260
> fix: fixed error with no expected value in `expandColumnTitle` slot

- components/table/hooks/useFilter/index.tsx
fix:  #7140 
fix:  #7160 
reference：https://github.com/ant-design/ant-design/blob/HEAD/components/table/hooks/useFilter/index.tsx#L218
> fix: table filter does not work in header group

- components/segmented/style/index.ts
当我给插槽里的标签添加title属性时，鼠标放上去是没有效果的，因为被:after伪类样式挡住了
> fix(segmented): title property in segmented component slot not effective

- components/select/index.en-US.md
- components/select/index.zh-CN.md
updating the `dropdownRender` description and jumps in the FAQ for Select
> docs[Select]: updating the `dropdownRender` description and jumps in the FAQ

- components/date-picker/locale/ja_JP.ts
Using the `< a-range-picker > `component of the Japanese internationalization configuration, when the `picker` attribute is set to `month`, the `placeholder` still displays "日付を選択 (select date)", which is not in line with expectations.
Although you can modify `placeholder` manually for the time being, you hope to solve this problem fundamentally.
Look at the source code and find that the relevant configuration is missing in the Japanese internationalization configuration. Therefore, it is supplemented and perfected in this pr.
使用日语国际化配置的 `<a-range-picker>` 组件，`picker` 属性设置为 `month` 时，`placeholder` 仍然显示 "日付を選択(选择日期)" 这不符合预期。
虽然可以暂时手动修改 `placeholder` ，但希望从根本解决此问题。
查看源代码发现日语国际化配置中缺少相关配置。故在此 pr 中补充完善。
> fix(locales): Update ja_JP.ts

- site/src/hooks/useSiteToken.ts
I found that there are two duplicate variable declarations `--mobile-max-width`.
> fix: remove duplicate style variable

- components/input/ResizableTextArea.tsx
最小复现代码：
```vue
<template>
<a-textarea v-model:value="inputValue" placeholder="Basic usage" auto-size />
</template>
<script lang="ts" setup>
import { ref, onMounted } from 'vue';
const inputValue = ref();
onMounted(() => {
inputValue.value = 'autoSize will not work';
});
</script>
```
> fix(Input): autoSize not work when change value in onMounted

- components/input/TextArea.tsx
- components/vc-input/Input.tsx
修复#7380 和 #7276 问题
复现步骤（必要条件：AutoComplete的默认插槽为InputSearch或TextArea组件时才会出现）：
问题1:
1. 首先输入中文
2. 点击输入框，中文自动消失
问题2:
1. 首先输入中文，输入完毕后删除所有中文字符
2. 再输入英文时无法正常输入
问题3:
1. 首先输入英文，输入完毕后删除所有英文字符
2. 再输入中文时，随便点击键盘中任意按键，中文消失
在初次输入中文时，`isCompositing`状态与手动设置的`e.target.composing`标志不同步。
> fix(AutoComplete): #7380 and #7276

- components/vc-slick/inner-slider.jsx
Antd vue  4.1.2
引入走马灯组件，使用 **beforeChange** 属性，发现返回的 **current** 的值始终为 **undefined**
https://codesandbox.io/p/sandbox/ji-ben-ant-design-vue-4-1-2-forked-pdrlxc?file=%2Fsrc%2Fdemo.vue%3A11%2C53
> fix[Carousel]: Fixed the current value returned by beforeChange props is incorrect

- components/vc-input/Input.tsx
修复因为修复input中午输入问题导致的input内部inputRef指向错误的问题，这个问题导致清空等操作报错
> fix: 修复inputRef指向错误问题

- site/src/vueDocs/getting-started.en-US.md
- site/src/vueDocs/getting-started.zh-CN.md
Add Vite and Rsbuild to the Getting Started guide 😄
The current Getting Started guide only contains Vue CLI, and Vue CLI is no longer maintained. So it would be better if we could recommend some modern tools like Vite and Rsbuild to users.
> docs: add Vite and Rsbuild to getting started

- components/space/style/index.tsx
Expect: The css selector does match '.ant-space-item:empty'.
Actual: It's '.ant-space-space-item:empty'
This PR fixes this issue.
> fix: empty space-item are not been hidden

- components/vc-select/Selector/SingleSelector.tsx
- components/vc-select/Selector/index.tsx
> fix[select]: fix placeholder error when inputting Chinese

- components/input-number/index.tsx
- components/input/Password.tsx
- components/input/TextArea.tsx
- components/input/calculateNodeHeight.tsx
Remove unnecessary assertions and use?? Instead of the ternary operator
删除不必要的断言和使用??代替三元运算符
> refactor(input): remove unnecessary assertions and use?? instead of the ternary operator

- components/grid/style/index.ts
close #7564 
fix issue with space-evenly not working
> fix(grid): add missing space-evenly alignment for grid-row

- components/vc-picker/PresetPanel.tsx
> RangePicker在getPopupContainer设置为`(el) => el.parentNode`时，点击preset时会触发两次onOpenChange，第一次为preset panel，open为false，第二次为事件冒泡到onPickerClick，open为true 
> 复现地址 https://stackblitz.com/edit/vitejs-vite-kjllhh?file=src%2Fcomponents%2FHelloWorld.vue 点击RangePicker，选择PresetPanel中的一个preset，日期选择面板消失后又出现
> PresetPanel的onClick阻止事件冒泡
> fix(PresetPanel): preset panel stopPropagation

- components/float-button/interface.ts
按照文档所述这里的 `target` 相当于 `a` 标签的 `target`。
那么 `_self`、`_blank`、`_parent`、`_top` 只是有特殊含义的关键字，并不能完全囊括 `target` 可以输入的内容，我们还可以传入 `framename` 用来在指定的 `<iframe>` 上打开URL链接
> fix(FloatButton): type error

- components/select/__tests__/index.test.js
- components/vc-select/BaseSelect.tsx
resolve #7819 
When the panel is closed, the focus variable of the select should also be reset to false.
> fix[Select]: fix select losing focus issue

- components/tree/index.en-US.md
- components/tree/index.zh-CN.md
> docs: Change the default values of attributes

- components/icon/index.en-US.md
- components/icon/index.zh-CN.md
为了优化项目性能，可迁移vue-cli项目到rsbuild全新方案
此PR是补全新方案的使用文档
> doc: Add custom icons to support Rsbuild documentation

- components/switch/demo/basic.vue
- components/switch/demo/size.vue
- components/switch/demo/text.vue
- components/switch/style/index.ts
首先，感谢你的贡献！ 😄
同步最新的cssvar特性
> 锚定版本 antd v5.22.1
1. Switch组件支持cssvar特性，样式同步为最新5.22.1
1. 剩余组件cssvar功能改造
2. 换肤编辑器重新同步最新版本功能
> feat[cssvar]: switch support cssvar

- components/tabs/index.en-US.md
Tabs component was missing "centered" in the API (although it exists as an example)
> docs: [Tabs] Added "centered" to API

- components/select/index.en-US.md
- components/select/index.zh-CN.md
https://github.com/vueComponent/ant-design-vue/blob/4a37016f4e3f829838b2e2b3cd128af220d67be8/components/config-provider/context.ts#L48
So, it's `middle`, not `default`. :grin:
> docs: correct possible `size` size in component Select

- README-zh_CN.md
- README.md
antd团队推出了专注于ai交互的[Antd Design X](https://github.com/ant-design/x)组件库。
我相应地创建了其Vue版本[Antd Design X Vue](https://github.com/wzc520pyfm/ant-design-x-vue)，功能已同步完成。
期望在Ecosystem添加仓库链接。
> chore: add ant-design-x-vue link at ecosystem

- components/breadcrumb/Breadcrumb.tsx
- components/breadcrumb/style/index.ts
1. Breadcrumb 组件支持 cssvar 特性，样式同步为最新 antd v5.26.1
> feat[cssvar]: Breadcrumb support cssvar

- components/skeleton/Avatar.tsx
- components/skeleton/Button.tsx
- components/skeleton/Image.tsx
- components/skeleton/Input.tsx
- components/skeleton/Skeleton.tsx
- components/skeleton/style/index.ts
1. Skeleton 组件支持 cssvar 特性，样式同步为最新 antd v5.26.1
> feat[cssvar]: Skeleton support cssvar

- components/avatar/Avatar.tsx
- components/avatar/Group.tsx
- components/avatar/style/index.ts
- components/badge/Badge.tsx
- components/badge/Ribbon.tsx
- components/badge/style/index.ts
- components/badge/style/ribbon.ts
- components/theme/interface/cssinjs-utils/index.ts
- components/theme/interface/cssinjs-utils/interface.ts
- components/theme/interface/index.ts
- components/theme/internal.ts
1. Avatar 组件支持 cssvar 特性，样式同步为最新 antd v5.26.1
2. Badge 组件支持 cssvar 特性，样式同步为最新 antd v5.26.1
> feat[cssvar]: Avatar & Badge support cssvar

- components/collapse/Collapse.tsx
- components/collapse/style/index.tsx
1. Collapse 组件支持 cssvar 特性，样式同步为最新 antd v5.26.1
> feat[cssvar]: Collapse support cssvar

- components/slider/style/index.tsx
- 组件样式改进
slider组件使用marks时最后一个dot无法点击
> fix(slider): fix slider last dot can’t click
