vueComponent/ant-design-vue

docs/vue/use-with-vue-cli.en-US.md, docs/vue/use-with-vue-cli.zh-CN.md
Use in vue-cli 3  =>  Use babel-plugin-import update
=> docs: update to vue-cli3

components/vc-notification/assets/index.less
=> style: 💄 vc-notification

components/icon/demo/custom.md
Added the template end tag missing from the custom icon demo.
> 3. Does this PR contains potential …
=> docs: update icon demo

components/upload/UploadList.jsx
目前ico格式的图片url没有预览显示
> 2. 要解决的问题。
支持icon格式的图片显示预览图
无
=> 支持icon格式的图片显示预览图

types/form/form.d.ts
=> add type definition for Form

components/tooltip/abstractTooltipProps.js, components/tooltip/index.en-US.md, components/tooltip/index.zh-CN.md
=> Fix tooltip destroy tooltip on hide

components/_util/ContainerRender.jsx
=> fix(ContainerRender): memory leak when invoke removeContainer

components/dropdown/style/index.less
The style of submenus for cascading menu is wrong.
Fix the disabled status of submenus for cascading menu.
> 3. GIF or snapshot should be provided if includes UI/interactive …
=> fix: submenu disalbed style

components/table/index.en-US.md
=> update table documentation

types/pagination.d.ts
=> 给分页器的配置项添加非必填标识

components/input/style/index.less
the input allowClear icon of current version is have a style bug with search icon
fix reference https://github.com/ant-design/ant-design/pull/15672
> 1. Does this PR affect user? Which part …
=> fix: input clear icon style

components/form/index.en-US.md, components/form/index.zh-CN.md
> 1. form表单组件，中英文文档中，setFieldsValue描述少了一个小括号
> 直接增加一个小括号
> 优化用户文档阅读体验
> 无
=> fix: error doc file in form components #1054

components/table/index.en-US.md, components/table/index.zh-CN.md
=> fix: '{' and ')' are not match

components/vc-collapse/src/Collapse.jsx
> 1. throw exception when has none collapse-panel in default slot
=> fix: throw exception when has none collapse-panel in default slot

components/transfer/demo/basic.md
In `Transfer` basic demo, there is a disable switch
In `Transfer` basic demo, there is a disable switch, to disable the transfer, when switch closed, transfer is enabled to edit, so the text on switch should be 'enable', not 'disable'
> If this PR related with other PR or following info. You can …
=> fix: [Transfer] basic demo codes issue

components/cascader/index.jsx
=> fix: cascader prop notFoundContent type typo

components/popconfirm/index.zh-CN.md
=> fix: docs typo

components/tree-select/index.en-US.md, components/tree-select/index.zh-CN.md
- maxTagCount
- maxTagPlaceholder
> 2. …
=> docs: add two props of treeselect

types/ant-design-vue.d.ts
=> Fix statistic ts type import path

components/vc-time-picker/Header.jsx, components/vc-time-picker/Panel.jsx
当使用backspace删除所有字符后，输入第一个字符控制台报错，并无字符显示
问题在于尝试在子组件改变prop showStr，但是并没有发现这个showStr实际带来了什么作用，目前方案是直接删除了，按照例子测试了一下，暂时没有发现副作用
https://github.com/vueComponent/ant-design-vue/issues/1173
> 2. List final API realization and usage …
=> fix: time-picker bug

components/_util/props-util.js
修复getComponentFromProp方法分支条件下无法获取v-slot对应值的bug
影响：select分组下自定义label、tabpane自定义tab以及其他使用的地方
> 1. …
=> fix: get slot value bug

components/_util/responsiveObserve.js, components/descriptions/Col.jsx, components/descriptions/__tests__/__snapshots__/demo.test.js.snap, components/descriptions/__tests__/demo.test.js, components/descriptions/demo/basic.md, components/descriptions/demo/border.md, components/descriptions/demo/index.vue, components/descriptions/demo/responsive.md, components/descriptions/demo/size.md, components/descriptions/demo/vertical-border.md, components/descriptions/demo/vertical.md, components/descriptions/index.en-US.md, components/descriptions/index.jsx, components/descriptions/index.zh-CN.md, components/descriptions/style/index.js, components/descriptions/style/index.less, components/index.js, components/style.js, components/style/themes/default.less, site/components.js, site/demo.js, site/demoRoutes.js, tests/__snapshots__/index.test.js.snap, types/ant-design-vue.d.ts, types/descriptions/descriptions-item.d.ts, types/descriptions/descriptions.d.ts
=> Feat descriptions

components/table/demo/colspan-rowspan.md
> I used a-table in my project for test, I found a piece of code is redundant and invalid. 
> Update colspan-rowspan.md  and remove this piece of code.
> If this …
=> docs: update colspan-rowspan.md

components/progress/style/index.less
> #1310 
> pretter Line progress style (#1310)
> 修正进度条方角边缘为显示问题 (#1310)
=> fix: pretter Line progress style (#1310)

components/comment/__tests__/__snapshots__/demo.test.js.snap, components/comment/index.jsx
修复comment组件多层级下样式错误的bug
> 2. What will …
=> fix: comment render nest style bug

types/ant-design-vue.d.ts
- https://github.com/vueComponent/ant-design-vue/issues/1194 …
=> fix: export Comment component

.huskyrc, package.json
=> feat: remove unit test commit hooks

components/tree/Tree.jsx
=> fix:Tree scopedSlots icon no work

components/_util/store/connect.jsx
=> fix: [subMenu]props

components/card/demo/tabs.md
=> docs: update card tabs demo

docs/vue/faq.en-US.md
- [* ] Site / document update
English version document correction.
Correct differences of the document between Chinese and English version.
No issue link.
- [*] Doc is not needed
- [*] Demo is not needed
- [*] TypeScript definition is not needed
- [*] Changelog is not needed
=> docs: update faq of en-US, syncing with zh-CN

docs/vue/introduce.en-US.md
- [* ] Site / document update
English version document correction.
Correct differences of the document between Chinese and English version.
No issue link.
- [*] Doc is not needed
- [*] Demo is not needed
- [*] TypeScript definition is not needed
- [*] Changelog is not needed
=> docs: update introduce of en-US, syncing with zh-CN

components/locale-provider/bg_BG.js
=> Fixed minor typo

types/carousel.d.ts, types/form/form-item.d.ts, types/upload.d.ts
=> fix(typo): form, carousel, upload. duplicate identifier

components/list/index.jsx
fix wrong locale variable
the List prop locale has no effect …
=> fix wrong locale variable

CHANGELOG.en-US.md
- [x ] Site / document update
> 2. …
=> docs: mod changelog

build/dev.js, build/webpack.base.conf.js, package.json, site/demoRoutes.js, site/index.js
=> Perf: highlight.js --> prism

types/form/form.d.ts
> 1. Using typescript,  an error occurred when specifying the name while executing the exec 'createForm' API.
> 2. Add name definition for create form option.
=> feat: add name definition for create form option

examples/App.vue, examples/index.html, examples/index.js, package.json, webpack.config.js
- [x ] Site / document update
> 2. …
=> feat: support npm run dev in primary repository

components/alert/index.jsx, components/message/index.js, components/modal/ConfirmDialog.jsx, components/modal/Modal.jsx, components/modal/index.js, components/vc-dialog/Dialog.jsx
=> feat: modal, alert and message use new icon

types/message.d.ts
[Message] The type is incomplete. 
I checked the antd / antdv source code and modified it.
=> fix(types): update [message] types

components/dropdown/__tests__/__snapshots__/demo.test.js.snap, components/dropdown/__tests__/__snapshots__/dropdown-button.test.js.snap, components/dropdown/dropdown-button.jsx, components/dropdown/dropdown.jsx
=> feat: update dropdown to new icon

components/layout/Sider.jsx, components/layout/__tests__/__snapshots__/demo.test.js.snap
=> feat: layout use new icon

types/table/column.d.ts
[Column] The type is incomplete.
I checked the antd / antdv source code and modified it.
=> fix(types): update [Column] types

components/timeline/Timeline.jsx, components/timeline/__tests__/__snapshots__/demo.test.js.snap
=> feat: update timeline icon

types/modal.d.ts
=> fix: destroyAll missing from modal.d.ts

package.json
- start 的命令好像是之前的吧，没更新
none
none
none
=> docs: fix package.json start

components/page-header/index.jsx, components/pagination/Pagination.jsx, components/popconfirm/index.jsx, components/progress/progress.jsx
=> feat:update page-header, pagination, popconfirm, progress icon

types/form-model/form.d.ts
[FormModel] The type is incomplete.
I checked the antd / antdv source code and modified it.
=> fix(types): update [FormModel] types

components/config-provider/index.jsx
- https://github.com/vueComponent/ant-design-vue/issues/2038 …
=> feat: add config direction

types/form/form.d.ts
=> feat: 明确 createForm 返回类型

components/badge/Badge.jsx, components/badge/style/index.less, components/badge/style/rtl.less, components/card/Card.jsx, components/card/style/index.less, components/card/style/rtl.less, components/transfer/index.jsx, components/transfer/operation.jsx, components/transfer/style/index.less, components/transfer/style/rtl.less, components/upload/Upload.jsx, components/upload/UploadList.jsx, components/upload/style/index.less, components/upload/style/rtl.less
- https://github.com/vueComponent/ant-design-vue/issues/2038 …
=> feat: add rtl badge/card/transfer/upload

components/button/button.jsx, components/button/style/index.less, components/button/style/rtl.less, components/grid/Col.jsx, components/grid/Row.jsx, components/grid/style/index.less, components/grid/style/rtl.less
- https://github.com/vueComponent/ant-design-vue/issues/2038 …
=> feat: add rtl button/grid

components/tabs/TabBar.jsx
renderTabBar is not work in Tab
https://github.com/vueComponent/ant-design-vue/issues/2157
> 1. …
=> fix: renderTabBar失效 #2157

components/table/style/index.less
=> fix: table-prefix-cls is not work in class 'ant-table-thead'

components/date-picker/style/RangePicker.less
- separator disabled color 未生效
- EN：Fix DatePicker separator color when disabled
- CN：修复 DatePicker 分隔符禁用时颜色
=> style: fix datepicker disabled color

.eslintrc, package.json
=> chore: eslint for markdown

components/tabs/tabs.jsx
fix: removeTab support 0 as key
> 2. …
=>  removeTab support 0 as key

components/dropdown/style/index.less
`@dropdown-vertical-padding` variable substitution has not effect on `<a>` in `<a-menu-item>` component.
> 3. GIF or snapshot should be provided if includes UI/interactive …
=> style: fix dropdown vertical padding variable substitution

components/vc-calendar/src/RangeCalendar.jsx
fix: RangeCalendar getEndValue adjust month if date not align condition incorrect, #2256 
#2256 
> …
=> fix: RangeCalendar getEndValue adjust month if date not align condition incorrect

components/vc-calendar/src/range-calendar/CalendarPart.jsx
refactor: CalendarPart dateInputElement has two onChange handler, remove the previous
> 1. Does …
=> refactor: CalendarPart dateInputElement has two onChange handler

components/_util/ant-ref.js, components/_util/props-util.js, components/drawer/index.jsx, components/vc-drawer/src/Drawer.js, examples/App.vue, examples/index.js
update drawer in vue3
API not change
=> feat: update drawer in vue3

components/alert/index.jsx
=> fix: configProvider is not a function

components/empty/index.jsx, examples/index.js
=> feat: update empty

components/comment/index.jsx, examples/index.js
=> feat: update comment

components/input/Password.jsx
首先，感谢你的贡献！ 😄
#2414 
参考 https://github.com/ant-design/ant-design/pull/23633
=> fix: input-password prevent  caret position

components/mentions/index.jsx, components/vc-mentions/src/Mentions.jsx
=> feat: mentions

components/vc-menu/Menu.jsx, webpack.config.js
=> chore: jsx use PatchFlags

components/grid/__tests__/__snapshots__/index.test.js.snap, components/grid/__tests__/index.test.js
=> test: update grid

components/menu/MenuItem.jsx
fix https://github.com/vueComponent/ant-design-vue/issues/2526
> 1. Does this PR affect user? …
=> fix: menu Item title setting

components/select/style/index.less, components/style/themes/default.less
close https://github.com/vueComponent/ant-design-vue/issues/2458
|- | Changelog|
|---|---|
|EN | Add `@select-item-select-color` to control the color when Select item is selected. |
|CN| 增加 `@select-item-selected-color` 以控制 Select 选项选中时的颜色。 |
=> style: add @select-item-selected-color

antd-tools/cli/index.js, antd-tools/cli/run.js, scripts/run.js
=> fix: 处理在 manjaro 下 colorful 样式无法生效

components/locale-provider/LocaleReceiver.jsx, components/pagination/MiniSelect.jsx, components/pagination/Pagination.jsx, components/pagination/index.js, components/vc-pagination/Pager.jsx, components/vc-pagination/Pagination.jsx
=> feat(pagination): upgrade to v3

breakChange-2.x.md, components/collapse/Collapse.jsx, components/collapse/CollapsePanel.jsx, components/collapse/__tests__/__snapshots__/index.test.js.snap, components/collapse/index.js, components/vc-collapse/src/Collapse.jsx, components/vc-collapse/src/Panel.jsx, components/vc-collapse/src/PanelContent.jsx
=> feat: update collapse

components/breadcrumb/Breadcrumb.jsx
=> fix: breadcrumb duplicate keys detected #2505

components/mentions/__tests__/index.test.js, components/vc-mentions/src/Mentions.jsx
=> fix: stop measure when pressing enter with empty result

types/anchor/anchor-link.d.ts, types/anchor/anchor.d.ts, types/ant-design-vue.d.ts, types/breadcrumb/breadcrumb-item.d.ts, types/breadcrumb/breadcrumb-separator.ts, types/breadcrumb/breadcrumb.d.ts, types/button/button-group.d.ts, types/button/button.d.ts, types/checkbox/checkbox-group.d.ts, types/checkbox/checkbox.d.ts, types/component.d.ts, types/meta.d.ts
typescript import type **error**
> typescript import type error
=> fix: install types

types/result.d.ts
=> chore: update type result

types/empty.d.ts
=> chore: update type empty

types/alert.d.ts
=> chore: update type alert

types/descriptions/descriptions-item.d.ts, types/descriptions/descriptions.d.ts, types/pub.ts
=> chore: update type descriptions

types/avatar.d.ts
=> chore: update type avatar

types/divider.d.ts
=> chore: update type divider

types/back-top.d.ts
=> chore: update type backtop

types/badge.d.ts
=> chore: update type badge

types/switch.d.ts
=> chore: update type switch

types/affix.d.ts, types/tag/checkable-tag.d.ts, types/tag/tag.d.ts
=> chore: update Affix and Tag type

types/comment.d.ts, types/timeline/timeline-item.d.ts, types/timeline/timeline.d.ts
> 3. Does this PR contains potential break change or …
=> chore: update comment and timeline type

types/list/list-item.d.ts, types/list/list.d.ts, types/meta.d.ts, types/table/column-group.d.ts, types/table/column.d.ts, types/table/table.d.ts
Update Table, List component typescript typo
=> chore: update table, list types

types/transfer.d.ts, types/tree-node.d.ts, types/tree/dictionary-tree.d.ts, types/tree/tree.d.ts
Update `Transfer` `Tree` component typescript typo.
=> fix: update transfer, tree types

types/tree-select.d.ts
Update `Tree-Select` component typescript typo
=> fix: update tree-select types

types/drawer.d.ts
=> chore: update type drawer

types/spin.d.ts, types/table/column-group.d.ts, types/table/column.d.ts, types/table/table.d.ts
=> chore: table props

types/mentions/mentions.d.ts, types/mentions/option.d.ts, types/notification.d.ts
=> chore: update type mentions

types/input-number.d.ts, types/message.d.ts
=> chore: update type message

types/input/input-group.d.ts, types/input/input-search.d.ts, types/input/input.d.ts, types/input/password.d.ts, types/input/textarea.d.ts
=> chore: update type input

types/dropdown/dropdown-button.d.ts, types/dropdown/dropdown.d.ts
=> chore: update type dropdown

types/menu/menu-item-group.d.ts, types/menu/menu-item.d.ts, types/menu/menu.d.ts, types/menu/sub-menu.d.ts
=> chore: update type menu

types/calendar.d.ts
Update `Calendar` component typescript typo
=> chore: update Calendar type

types/date-picker/common.d.ts, types/date-picker/date-picker.d.ts, types/date-picker/month-picker.d.ts, types/date-picker/range-picker.d.ts, types/date-picker/week-picker.d.ts
Update `DatePicker`, `MonthPicker`, `RangePicker`, `WeekPicker` typescript typo
=> chore: update DatePicker types

types/button/button-group.d.ts, types/button/button.d.ts, types/carousel.d.ts
Update `Carousel`, `Button` component typescript typo
=> chore: update Carousel, Button type

types/config-provider.d.ts
Update `ConfigProvider` component typescript typo
=> chore: update ConfigProvider type

types/skeleton.d.ts
Update `Skeleton`  component typescript typo
=> chore: update Skeleton type

components/badge/Badge.jsx, components/badge/__tests__/__snapshots__/index.test.js.snap, components/badge/__tests__/index.test.js, types/badge.d.ts
=> feat: badge text support vnode

types/menu/menu.d.ts
=> chore: add menu onClick ts type

types/progress.d.ts
=> chore: add size type to progress

types/button/button.d.ts
Button component type prop missing  'link' 
#2853
> 3. Does this PR contains potential break …
=> fix(types): button type prop missing link

components/vc-tabs/src/TabPane.jsx
1. fixed tabs components vue warning
2. warning info: `setup() return property "_isActived" should not start with "$" or "_" which are reserved prefixes for Vue internals.`
> 1. Does this PR …
=> fix(vc-tabs): tabs vue warning

types/card.d.ts
=> chore: update card type

types/tootip/tooltip.d.ts
=> chore: update tooltip type

types/card.d.ts, types/input/input-search.d.ts, types/input/input.d.ts, types/input/password.d.ts, types/page-header.d.ts, types/tag/tag.d.ts
update the props types of some components
> 3. Does this PR contains potential break change or …
=> update the props types of some components

components/upload/Upload.jsx
issue #2883
> If this PR related with other PR or following info. You …
=> fix(upload): button will disappear when count meets limitation

types/checkbox/checkbox-group.d.ts, types/checkbox/checkbox.d.ts
=> fix(types): checkbox and checkbox-group props types

components/tree/DirectoryTree.jsx, components/tree/util.js
=> 修复 a-directory-tree bug

types/input/textarea.d.ts
=> fix(types): textarea props types

components/space/index.jsx
首先，感谢你的贡献！ 😄
为`Space`组件设置`class`或`style`。
> 2. 要解决的问题。
`Space`为函数式组件，在父组件上设置的`class`和`style` 默认不会应用到`Space`的根元素上。
[![Edit Vue Antd Template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-9tstt?fontsize=14&hidenavigation=1&theme=dark)
> 1. 英文描述
> 2. 中文描述（可选）
=> fix: space can not inherit attrs

components/vc-select/Select.jsx
=> fix(select): click on the selected item can deselect

components/tree/Tree.jsx
当有使用全局对title做自定义操作需求时（例如右键菜单，操作项），可以直接通过slot直接定义全局自定义title，而不是在treeData中每个都进行slots拼接
> 1. Does …
=> feat: tree support global title slot

components/form/style/index.less, components/input/ClearableLabeledInput.jsx, components/input/Input.jsx, components/input/style/index.less, components/input/style/mixin.less, components/style/themes/default.less
-  suffix 传入的字符串或者组件的宽度过长，就会导致input框的内容与 suffix 重叠
- 当input组件存在 suffix 、 prefix 或者 allowClear 的情况下传入的 style 无法生效的问题
``` vue
// style is invalid 
<a-input prefix="￥" suffix="RMB" style="width: 100px" />
```
- allowClear 的图标与 suffix 和 input 内容区域过于接近
> 3. GIF or snapshot …
=> refactor(input): update input style

components/date-picker/WeekPicker.tsx, components/date-picker/interface.ts
=> fix(date-picker): import path

components/modal/ConfirmDialog.jsx, components/modal/__tests__/confirm.test.js
=> 2.x title props support render function

components/modal/ConfirmDialog.jsx, components/modal/__tests__/confirm.test.js
=> fix(modal): title props support render function

components/input/ClearableLabeledInput.jsx, components/input/TextArea.jsx, components/input/__tests__/__snapshots__/index.test.js.snap, components/input/__tests__/index.test.js, components/input/style/index.less, types/input/textarea.d.ts
=> feat: textarea support word count

components/alert/index.tsx
=> fix(alert): fix alert class not work

components/input/style/mixin.less
=> feat: add input wrapper style

components/input/Input.tsx, components/input/Password.tsx, components/input/ResizableTextArea.tsx, components/input/Search.tsx, components/input/TextArea.tsx
- TypeScript definition update
=> chore: declare input type

components/form/utils/validateUtil.ts
show advice when others face the same …
=> fix: add warning when validating form for non-string type

components/form/Form.tsx
> 1. The type of the rules(Form) should be an object instead of an array.
=> fix(form): form rules type error

components/auto-complete/style/index.less
close https://github.com/vueComponent/ant-design-vue/issues/3140
CN：修复 AutoComplete 设置 `disabled` 背景色异常的问题。
EN：Fix the problem that the background color of AutoComplete setting `disabled` is abnormal.
=> fix: auto-complete disabled bg

components/list/index.tsx, components/table/interface.ts
=> fix: pagination type error #3159

components/form-model/Form.jsx, components/form/Form.jsx, types/form-model/form.d.ts, types/form/form.d.ts
The type of message comes from the library async-validator and it has been updated: https://github.com/yiminghe/async-validator/pull/251/files
This PR is to keep ant-design-vue up to date with that change.
=> Update ValidationRule message type

components/style/themes/default.less, components/tag/style/index.less
=> feat: tag support status color

components/menu/index.tsx
=> fix: update Menu type

components/tag/index.tsx
=> feat: tag support icon slot

components/notification/index.tsx
https://github.com/vueComponent/ant-design-vue/issues/3182
CN: 修复 Notification `top` `bottom` 类型定义。
EN: Fix the type definition of Notification `top` `bottom`.
=> fix: notification top type

components/message/index.tsx
=> chore: fix Message type

components/input-number/index.tsx
> 1. InputNumber lose onChange props
=> fix(input-number): fix InputNumber onChange type error

.github/workflows/need-reproduce.yml
目前 issue 增加 need-reproduce，创建者无法准确获取管理者意图。
新增 Actions 自动评论。
ref: https://github.com/vueComponent/ant-design-vue/issues/3226
=> chore: create need-reproduce.yml

components/dropdown/dropdown-button.tsx, components/dropdown/dropdown.tsx
=> chore: add dropdown emits

components/tooltip/Tooltip.tsx, components/tooltip/placements.ts
=> chore: fix tooltip type

components/button/style/mixin.less
=> Fix button group style

components/button/style/mixin.less
=> fix(button): dropdown button in the wrong position

components/date-picker/RangePicker.tsx
=> fix: range-picker style order #3219

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> update: about import icon in change log

components/input/TextArea.tsx
=> fix: input lose style #3273

components/vc-menu/Menu.jsx
如果openkeys被设为undefined，会导致indexOf取不到值 …
=> fix: indexof openkeys error

types/ant-design-vue.d.ts, types/space.d.ts
=> fix(d.ts): space.d.ts  #2923 typeScript definition update

components/date-picker/props.ts
=> remove unsed codes in components/date-picker/props.ts

components/vc-slider/src/utils.js
=> fix: slider accuracy problems #3346

components/vc-slider/src/utils.js
=> fix: slider accuracy problems 1.x

components/layout/Sider.tsx
=> fix: layout-sider class

.github/workflows/issue-reply.yml, .github/workflows/need-reproduce.yml
=> ci: update need reproduce

components/select/index.tsx, components/tree-select/index.tsx, components/vc-select/OptGroup.tsx, components/vc-select/Option.tsx, components/vc-tree-select/src/SelectNode.jsx
=> chore: remove all hard code component name

components/empty/style/index.less
=> chore: remove duplicate style

components/tooltip/style/index.less
=> fix: upgrade to less4 syntax  #3477

components/vc-image/src/Image.tsx
> When preview is an object, the console will issue a warning
> fix
=> fix(image): fix iamge prop error

components/vc-progress/src/Circle.js
fix https://github.com/vueComponent/ant-design-vue/issues/3487
see https://github.com/react-component/progress/pull/96
=> fix: add opacity transition #3487

components/vc-progress/src/Circle.js
=> fix: add opacity transition

components/tabs/TabBar.tsx, components/tabs/style/index.less, components/tabs/tabs.tsx
> 1. ant design(react) 's feature
> 2. add tab bar centered style
> 3. #3497 
> 1. add a new api `centered`
> 1. centered tabs
> 2. 可将 tabs 居中显示
> todo: docs and demos
=> feat(tabs): add centered tab bar style

package.json, scripts/postinstall.js
=> chore: remove node-emoji

components/date-picker/props.ts
> 1. bug fix
> 2. prop type check failed problem
> 3. #3463 
none
none
> 1. fix date-picker'props mode value: decade
> 2. 修复 date-picker 属性 mode 的值：decade
none
=> fix(date-picker): add props(mode) value -- decade

components/date-picker/interface.js
> issue: #3463 
> pr for 2.x(merged): #3514 
> 1. fix date-picker'props mode value: decade
> 2. 修复 date-picker 的属性 mode 的值：decade
=> fix(date-picker): fix props(decade) problem for 1.x

components/breadcrumb/BreadcrumbSeparator.tsx
=> fix: breadcrumb separator display

components/form/style/index.less
=> fix: form-item wrong line break

components/input/Search.tsx
> 1. Input.Search 传递 class 属性应该生效.
> 2. Input.Search 传递 class 属性生效.
> 3. https://github.com/vueComponent/ant-design-vue/issues/3539 …
=> fix: Input.Search指定class无效

components/vc-checkbox/src/Checkbox.jsx
=> fix: checkbox emit unexpected value

components/vc-tabs/src/Tabs.jsx
=> fix: disabled tabPane can be actived #3575

components/dropdown/getDropdownProps.ts
=> fix: correct dropdown trigger type

components/style/themes/default.less, components/table/style/index.less
=> style: move color var of table to default less

components/form/utils/validateUtil.ts
=> chore: improve form warning

components/tree/Tree.tsx
=> fix: improve tree type definition

components/modal/style/confirm.less
=> fix: closeable icon support in modal method

components/vc-menu/MenuItem.jsx
=> fix: table filter

components/menu/MenuItem.tsx
=> fix: menu-item type definition #3661

components/form/Form.tsx, components/form/FormItem.tsx, components/form/index.tsx
=> fix: improve form type definition #3638

antd-tools/gulpfile.js
>
> Replace `style` with `style/css`
>
> ![image](https://user-images.githubusercontent.com/8555127/108186973-f5c75f00-7148-11eb-9652-91aeb42b8499.png)
> 3. GIF or snapshot should …
=> chore: update css.js build #3678

components/vc-virtual-list/hooks/useMobileTouchMove.ts
=> fix: select scorll in mobile

.github/workflows/translate.yml
=> ci: create translate.yml

.github/workflows/translate.yml
=> ci: update translate

.github/workflows/translate.yml
=> ci: update translation helper

components/calendar/index.tsx, components/input/Search.tsx, components/vc-pagination/Pagination.jsx, components/vc-switch/Switch.jsx
=> fix: update data before callback

.github/workflows/stale.yml
=> chore: update state.yml

.github/workflows/issue-close-require.yml
`🤔 Need Reproduce`
3天未活跃 关闭 issue
每天查询一次
=> ci: create issue-close-require.yml

components/style/themes/default.less
首先，感谢你的贡献！ 😄
当使用暗黑主题时，Table 组件行选中后颜色改进。
> 2. 要解决的问题。
无
使用 ant-design中的颜色。
无
> 1. 英文描述
> 2. 中文描述（可选）
=> style: change table row color when selected in dark theme

components/form/style/index.less, components/input/style/mixin.less
=> refactor: update select style

components/modal/Modal.jsx
=> refactor: add Modal `dialogStyle` props

components/card/Card.jsx
=> fix: revert the default tab size of card

components/back-top/index.tsx
=> fix 'ABackTop visible issue under KeepAlive'

components/vc-table/src/TableCell.jsx
=> fix: use toRaw to solve error #3751

components/vc-input-number/src/index.js
issue #3814 
pr #3550
same bug
=> fix: Microsoft input triggers onchange twice

components/modal/ConfirmDialog.tsx, components/modal/Modal.tsx
=> fix: modal.confirm closable invalid

components/vc-upload/src/Upload.jsx
> 1. upload component method props not work
=> fix:upload component method props not work

components/vc-select/OptionList.tsx
=> fix: select always trigger first active

components/vc-select/utils/legacyUtil.ts
=> fix: opt group label

components/vc-select/util.js
=> fix: select trigger disabled option

components/table/ColumnGroup.tsx
=> feat (table): Support fixed group header (#3882)

antdv-demo/docs/table/index.zh-CN.md
=> docs(table): change rowSelection.selections's default value in chinese docs

CHANGELOG.zh-CN.md
=> docs: fix typo

antdv-demo/docs/table/index.en-US.md, antdv-demo/docs/table/index.zh-CN.md, components/table/ColumnGroup.jsx
=> feat(tbale): 分组表头支持固定-1.x

components/calendar/Header.tsx
=> fix: The calendar month shows 12 more

components/cascader/index.tsx
=> chore(cascader): fix types

components/input/Input.jsx
=> fix(input): `v-model` modifiers not work

components/alert/index.tsx
1. alertProps类型不必使用函数
2. 使用公共的getPropsSlot方法
=> chore: update Alert

components/badge/Badge.tsx, components/badge/utils.ts
=> chore: remove duplicate func

antdv-demo/components/header.vue
=> docs: keep current path when switching versions

components/upload/Upload.tsx
=> fix(upload): fix `process` is not defined when using vite

components/table/index.tsx
=> feat: table column support v-for #3934

components/input/Search.tsx, package.json
=> chore: remove is-mobile

components/radio/style/index.less
=> fix(2.x/radio): replace 'outline' with 'box-shadow'

components/radio/style/index.less
=> fix(1.x/radio): replace 'outline' with 'box-shadow'

components/vc-image/src/Image.tsx, components/vc-image/src/Preview.tsx
=> fix: image preview not work #3701

components/table/__tests__/__snapshots__/demo.test.js.snap
=> test: update table test case

components/input-number/index.jsx, components/vc-input-number/src/index.js
=> fix: input-number ready not work #2971

components/vc-menu/Menu.jsx
=> fix: always make selectedKeys be array #3978

.github/workflows/test.yml, components/form/__tests__/__snapshots__/demo.test.js.snap
=> chore: remove ci token

components/switch/index.tsx
=> fix(switch): add some missing types

components/vc-select/Selector/index.tsx
=> fix: import path

components/typography/Base.tsx
=> fix(typography): `editable` should not trigger links #4015

components/style.ts
=> fix: './carousel/style' imported two times.

components/vc-input-number/src/index.js
=> fix: input-number type not work

components/back-top/backTopTypes.ts, components/back-top/index.tsx, components/back-top/style/index.less
> 同步了 antd@4.4.0 的 back-top 组件 API
=> refactor(v3/back-top): use composition api

components/vc-time-picker/TimePicker.jsx
=> TimePicker input should be readonly like DatePicker

components/anchor/Anchor.tsx, components/anchor/AnchorLink.tsx, components/anchor/__tests__/Anchor.test.js
=> refactor(v3/anchor): use composition api

components/badge/Badge.tsx, components/badge/ScrollNumber.tsx, components/badge/style/index.less, components/style/themes/default.less
=> refactor(v3/badge): use composition api

components/input-number/index.tsx
=> refactor(input-number): export props types #4115

components/_util/hooks/useRef.ts, components/rate/Star.tsx, components/rate/index.tsx, components/rate/style/index.less, components/rate/style/rtl.less, components/rate/util.ts, components/style/themes/default.less
=> refactor(v3/rate): use composition api

components/tabs/tabs.tsx
=> fix: remove flex check

components/vc-virtual-list/List.tsx
=> fix: select dropdownMatchSelectWidth invalid #4118

components/tree-select/index.tsx, components/vc-tree-select/src/SearchInput.jsx
=> fix(vc-tree-select): `showSearch=false` is invalid #4119

antdv-demo/docs/popover/demo/hover-with-click.md
=> docs(popover): update style #4167

components/statistic/Countdown.tsx
=> fix(countdown): onFinish cannot trigger

components/descriptions/Cell.tsx, components/descriptions/Row.tsx, components/descriptions/__tests__/__snapshots__/index.test.js.snap, components/descriptions/__tests__/index.test.js, components/descriptions/index.tsx, components/descriptions/style/index.less, components/descriptions/style/rtl.less
sync with ant-design 4.16.3
> 2. What …
=> feat: update descriptions

components/_util/hooks/useConfigInject.ts, components/list/Item.tsx, components/list/ItemMeta.tsx, components/list/index.tsx, components/list/style/bordered.less, components/list/style/customize.less, components/list/style/index.less, components/list/style/rtl.less, components/pagination/Pagination.tsx, components/pagination/index.ts, components/style/themes/default.less, components/table/interface.ts
=> refactor: list

components/auto-complete/index.tsx
=> fix(auto-complete): support `options` slots #4012

components/dropdown/dropdown.tsx, components/style/themes/default.less, components/transfer/ListItem.tsx, components/transfer/index.tsx, components/transfer/list.tsx, components/transfer/operation.tsx, components/transfer/renderListBody.tsx, components/transfer/search.tsx, components/transfer/style/customize.less, components/transfer/style/index.less, components/transfer/style/index.ts, components/transfer/style/rtl.less
=> refactor(transfer): use composition api

components/components.ts
- [✅] Bug fix
1. `ant-design-vue` not exports name `UploadDragger` by using `vite-plugin-components`. …
=> fix(UploadDragger): fix UploadDrager no export

components/table/interface.ts
```
Error: node_modules/ant-design-vue/lib/table/interface.d.ts(131,9): error TS2411: Property 'title' of type 'string | undefined' is not assignable to string index type 'string'.
Error: node_modules/ant-design-vue/lib/table/interface.d.ts(132,9): error TS2411: Property 'filterIcon' of type 'string | undefined' is not assignable to string index type 'string'.
Error: …
```
=> fix TypeScript definition of Table interface for typescript 4.3.5

components/notification/index.tsx
首先，感谢你的贡献！ 😄
1. notification api类型粗暴的直接any，这边改过来
=> fix(notification): perfect notification type

package.json
Reverts vueComponent/ant-design-vue#4304
=> Revert "chore(deps): update dependency husky to v7"

components/vc-tree-select/src/Select.jsx, components/vc-tree-select/src/Selector/MultipleSelector/index.jsx, components/vc-tree-select/src/Selector/SingleSelector.jsx
=> feat: tree-select support showArrow

components/vc-mentions/src/mentionsProps.ts
=> refactor(vc-mentions): update types #4366

components/input/Password.tsx
=> feat(input-password): accept global prefixCls

components/empty/index.jsx
=> fix(empty): cannot get `prefixCls` in `configProvider`  #4446

antdv-demo/docs/avatar/demo/index.vue, antdv-demo/docs/badge/demo/index.vue, antdv-demo/docs/breadcrumb/demo/index.vue, antdv-demo/docs/checkbox/demo/index.vue, antdv-demo/docs/collapse/demo/index.vue, antdv-demo/docs/comment/demo/index.vue, antdv-demo/docs/divider/demo/index.vue, antdv-demo/docs/dropdown/demo/index.vue, antdv-demo/docs/empty/demo/index.vue, antdv-demo/docs/input-number/demo/index.vue, antdv-demo/docs/layout/demo/index.vue, antdv-demo/docs/list/demo/index.vue, antdv-demo/docs/mentions/demo/index.vue, antdv-demo/docs/message/demo/index.vue, antdv-demo/docs/notification/demo/index.vue, antdv-demo/docs/popconfirm/demo/index.vue, antdv-demo/docs/popover/demo/index.vue, antdv-demo/docs/radio/demo/index.vue, antdv-demo/docs/rate/demo/index.vue, antdv-demo/docs/skeleton/demo/index.vue, antdv-demo/docs/steps/demo/index.vue, antdv-demo/docs/timeline/demo/index.vue, antdv-demo/docs/tooltip/demo/index.vue, antdv-demo/docs/transfer/demo/index.vue, antdv-demo/docs/tree-select/demo/index.vue, antdv-demo/docs/tree/demo/index.vue, antdv-demo/docs/upload/demo/index.vue
> 1. 组件搜索，搜索组件名不能，有时不能出现中文文档.
> 2. 在组件中文描述处，增加英文名称，中英文之间加了空格.
> 3. 其他：Skeleton 增加骨架屏描述.
> 3. Does …
=> docs(update): update documents

antdv-demo/docs/space/demo/index.vue
=> docs(space): update `space` document layout #4426

components/tree-select/index.tsx
=> fix(tree-select): wrong title slot

components/vc-collapse/src/Collapse.jsx
=> refactor(vc-collapse): `key` support number type #4405

components/_util/type.ts, components/breadcrumb/Breadcrumb.tsx
=> chore(all): delete useless Omit define

components/date-picker/generatePicker/generateRangePicker.tsx, components/date-picker/generatePicker/generateSinglePicker.tsx, components/date-picker/generatePicker/index.tsx
=> fix: date-pick type error

components/switch/__tests__/index.test.js, components/switch/index.tsx
=> fix(switch): custom checkedChildren unexpected

components/style/mixins/clearfix.less
see 
https://github.com/ant-design/ant-design/issues/21103
pr 
https://github.com/ant-design/ant-design/pull/21109
https://github.com/ant-design/ant-design/pull/21314
https://github.com/ant-design/ant-design/pull/21867
close #4554
> 3. GIF or snapshot should be provided …
=> fix: remove zoom(#4554)

components/auto-complete/index.tsx
=> fix(auto-complete): cannot use configProvider prefixCls #4566

components/auto-complete/index.jsx
=> fix(auto-complete): cannot use configProvider prefixCls  #4566

components/vc-image/src/Image.tsx
=> refactor(vc-image): fix `imageProps` type #4583

components/select/index.en-US.md
=> docs(select): add tip

components/modal/Modal.tsx
=> fix(Modal): type-definition error

components/tag/index.tsx
> 1. 关闭 icon prefixCls 为 [object Object]，导致样式失效。
> 3. Does this PR contains potential break change …
=> fix(tag): prefixCls value

components/vc-tree-select/src/Base/BaseSelector.jsx
value为undefined或null不可被选中，无需判断
close #4648
> 3. Does this PR contains potential break change or …
=> fix: tree-select clear button render #4648

components/calendar/dayjs.tsx, components/calendar/generateCalendar.tsx, components/config-provider/index.tsx, components/date-picker/generatePicker/generateRangePicker.tsx, components/date-picker/generatePicker/generateSinglePicker.tsx, components/date-picker/generatePicker/index.tsx, components/date-picker/generatePicker/interface.ts, components/date-picker/generatePicker/props.ts, components/time-picker/time-picker.tsx
=> fix: typescript compile error

components/table/Table.jsx
> 1. 点击表格checkbox，在单元格较多的情况下有明显的卡顿。
> 2. 希望能提高该场景下的性能。
> 3. [#3987](https://github.com/vueComponent/ant-design-vue/issues/3987)
问题定位：在check事件回调中会更新一个变量（该变量储存了当前点击位置的索引，用于鼠标加shift批量选择时的逻辑判断）。由于该变量是响应式的，会触发table的render，导致每次点击后表格重新渲染，引发性能问题。
解决方案：该变量并不直接参与视图更新，没有响应式的必要。去除该变量的响应式即可。
> 3. Does …
=> fix(table): checkbox performance

components/input/Input.jsx
=> fix(input): allowClear in ie11 #4679

components/vc-tree-select/hooks/useTreeData.ts, components/vc-tree-select/interface.ts
=> fix(tree-select): checkable & selectable invalid

components/select/demo/search.vue
=> docs: update select component doc

antdv-demo/theme/template/IconDisplay/CopyableIcon.vue
修复复制icon没有theme的bug
> 2. What will say …
=> fix: copy icon #4389

components/form/useForm.ts
> 1.  When use useForm with ruleRef === undefined, it will log the warning that watch source is undefined
> 2. If ruleRef === undefined, no watch
> 3. #4881 
https://github.com/vueComponent/ant-design-vue/issues/4881
#4881
=> fix: useForm ruleRef undefined warning  #4881

site/src/utils/generateOnlineDemo.ts
=> docs: fix the incorrect version of antdv in codesandbox

components/icon/demo/basic.vue, components/icon/demo/custom.vue, components/icon/demo/two-tone.vue, components/icon/index.en-US.md, components/icon/index.zh-CN.md, site/src/theme/template/IconDisplay/CopyableIcon.vue
Close #4816
Change component name casing in document. Details are [#4816](https://github.com/vueComponent/ant-design-vue/issues/4816).
Convert the name of icon components to kebab-case.
Issue: https://github.com/vueComponent/ant-design-vue/issues/4816
- Convert examples to kebab-case style.
- Copy kebab cased icon name in examples.
`<UpOutlined />` => `<up-outlined />`
Only the document will be affected.
Nothing.
> 3. …
=> fix name casing in doc

components/rate/index.tsx
=> fix(rate): global prefixCls invalid

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, site/src/vueDocs/migration-v3.en-US.md, site/src/vueDocs/migration-v3.zh-CN.md
=> docs: modify typos in migration v3

components/vc-calendar/src/RangeCalendar.jsx
=> fix(range-picker): typo #5036

package.json
The deep-assign is no longer used. 
> …
=> chore: remove deep-assign

components/form/FormItem.tsx
=> fix(form-item): validate logic

site/src/vueDocs/getting-started.en-US.md, site/src/vueDocs/getting-started.zh-CN.md, site/src/vueDocs/use-with-vue-cli.en-US.md, site/src/vueDocs/use-with-vue-cli.zh-CN.md
=> docs: remove appconfig.productionTip

README-zh_CN.md, README.md, site/src/layouts/Footer.vue
=> docs(next): add @formily/antdv link

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, site/src/vueDocs/migration-v3.en-US.md, site/src/vueDocs/migration-v3.zh-CN.md
=> docs: fix typos and uniform punctuation in migration v3

components/modal/Modal.tsx
=> fix:(modal): getContainer property invalid

antdv-demo/docs/table/demo/edit-row.md
=> docs: table demo optimize

site/src/vueDocs/getting-started.en-US.md, site/src/vueDocs/getting-started.zh-CN.md
=> doc: add usage for vite

components/image/__tests__/__snapshots__/demo.test.js.snap, components/image/demo/controlledPreview.vue, components/image/demo/index.vue
=> docs(image): add controlled preview demo

components/_util/wave.tsx
首先，感谢你的贡献！ 😄
> 1. 修改全局perfixCls后,发现Button按钮没有水波纹特效。
> 1. 英文描述
> 2. 中文描述（可选）
=> fix: wave's custom prefixCls not working

components/modal/Modal.tsx
=> feat(components): [modal] export modalProps

components/checkbox/Checkbox.tsx
> 1.  the source of requirement.
The label onclick event is triggered twice, while I expect it to just trigger once
> 3.  issue link.
> 1. Basic  of  and other optional proposal.
> 3. GIF or snapshot should be  if includes UI/interactive modification.
> 1. Does this PR affect user? Which part will be …
=> fix(checkbox): onClick event triggered twice

components/_util/EventInterface.ts, components/auto-complete/__tests__/__snapshots__/demo.test.js.snap, components/vc-select/Selector/Input.tsx
=> refactor(v3/vc-selector/input): use composition api

components/vc-picker/panels/TimePanel/TimeBody.tsx
https://github.com/vueComponent/ant-design-vue/issues/5383
> 3. Does this PR contains potential …
=> fix(TimeRangePicker): disabledTime does not work，close #5383

components/grid/demo/playfround.vue, components/steps/demo/step-next.vue
=> docs: perf dark

components/vc-dialog/Content.tsx
=> fix(modal): style prop support string constant

components/alert/index.tsx, components/avatar/Avatar.tsx, components/input/ResizableTextArea.tsx, components/layout/Sider.tsx, components/tabs/src/TabPanelList/TabPane.tsx, components/vc-slider/src/Handle.tsx, components/vc-trigger/Popup/PopupInner.tsx
如果用户传递的`style`是一个字符串变量的话，这时候如果将`attrs.style`当成对象解构就会有一些问题，将之前对象解构的形式改为数组，不影响之前的功能或行为，仅是为了避免一些可能存在的问题 …
=> refactor(style): destructuring style change to array

components/date-picker/index.zh-CN.md
before:
after：
**PS：对应英文文档没有多余的中括号。**
> 3. Does this PR contains potential break change or other …
=> docs(DatePicker): remove redundant square brackets

components/descriptions/index.en-US.md, components/descriptions/index.zh-CN.md
=> docs(descriptions): fix markdown syntax issue

components/divider/index.en-US.md, components/divider/index.zh-CN.md
=> docs(descriptions): [API] fix type definition

components/dropdown/index.zh-CN.md, components/dropdown/props.ts
=> docs(dropdown): make type definitions more beautiful

components/mentions/index.en-US.md, components/mentions/index.zh-CN.md
=> docs(mentions): fix notFoundContent props type definition

components/dropdown/index.zh-CN.md
=> docs(dropdown): remove redundant periods

components/menu/index.en-US.md, components/menu/index.zh-CN.md
=> docs(menu): update type definition

components/select/index.en-US.md, components/select/index.zh-CN.md
=> docs(select): update type definition

components/message/index.en-US.md, components/message/index.zh-CN.md
=> docs(message): remove redundant props

components/result/index.en-US.md, components/result/index.zh-CN.md
=> docs(result): fix markdown syntax issue

components/tag/index.en-US.md, components/tag/index.zh-CN.md
=> docs(tag): update type definition

components/upload/index.en-US.md, components/upload/index.zh-CN.md
=> docs(upload): fix markdown syntax issue

components/rate/index.en-US.md, components/rate/index.zh-CN.md
=> docs(rate): update type definition

components/input/index.en-US.md, components/input/index.zh-CN.md
=> docs(text-area): fix markdown syntax issue

components/typography/index.en-US.md, components/typography/index.zh-CN.md
=> docs(typography): remove redundant props

components/config-provider/index.en-US.md, components/config-provider/index.zh-CN.md
=> docs(config-provider): remove redundant vertical bars

components/modal/index.en-US.md, components/modal/index.zh-CN.md
=> docs(modal): update type definition

components/tree/index.en-US.md, components/tree/index.zh-CN.md
before:
after:
> 3. Related issue link.  #5484 
=> doc: update tree switchIcon props type description

components/input/Input.tsx
fix: #5177, #5504, #5503, #5509
复现问题版本：vue 3.2.33
这个warning算是vue的问题吧！我们要不暂时先这么处理：把属性值为`undefined`的`prop`过滤掉，这样一来对`Input`原来的功能也不影响，只是暂时解决`Vue warn`问题，我同时也给vue提了一个相关[PR](https://github.com/vuejs/core/pull/5734)
before：
after：
> 3. GIF or snapshot should be provided if …
=> fix(Input): fix warning about failed setting prop size on input element

components/upload/index.en-US.md, components/upload/index.zh-CN.md
**before**: the `showUploadList` prop miss the `showDownloadIcon` option
**after**: add the `showDownloadIcon` option
> 2. What …
=> docs(upload): update `showUploadList` prop

components/table/Table.tsx, components/vc-table/Table.tsx
=> fix(Table): expandFixed prop type definition

components/drawer/index.tsx
=> fix(Drawer): closeIcon customization is invalid

components/vc-checkbox/Checkbox.tsx
[#5678](https://github.com/vueComponent/ant-design-vue/issues/5678)
> 3. Does this PR contains …
=> fix: checkbox set additional attribute no work，close #5678

site/src/theme/static/footer.less
make footer's z-index less than back-top's z-index #5691
=> fix(site) make footer's z-index less than back-top's z-index

components/carousel/demo/customPaging.vue
优化carousel中demo的代码写法
> If this PR related with other PR or following …
=> doc(carousel): using getImgUrl function in customPaging demo

components/vc-image/src/Preview.tsx
https://github.com/vueComponent/ant-design-vue/issues/5700
Mouse wheel doesn't zoom in and out of pictures.
Confirm that [ant-desgin](https://ant.design/components/image-cn/) image can zoom in and zoom out with the mouse wheel.
> 3. GIF or snapshot should be provided if …
=> feat(Image): Image support mouse wheel zoom in and out #5700

components/input/inputProps.ts
=> fix: add boolean type to autosize prop

package.json
Set the minimum running node version v12.22.0. Avoid dependency installation failure due to too low node version. The following is the exception that I installed dependencies in local low version.
```
error @typescript-eslint/eslint-plugin@5.30.3: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got “12.20.1”
```
> 1. …
=> chore(build): set minimum running node version v12.22.0

antd-tools/getWebpackConfig.js, index.js, package.json, webpack.build.conf.js
=> chore: bundle esm output

components/form/demo/normal-login.vue
=> doc(site): fix Login Form style

components/divider/style/index.less, components/style/themes/default.less, components/style/themes/variable.less
Make horizontal gutter of `<Divider />` customizable via less variable.
Similar with the vertical gutter variable.
No breaking changes.
1. English description
add `@divider-horizontal-gutter` less variable
2. Chinese description (optional)
新增 `@divider-horizontal-gutter` less 变量
Use CSS vars in the `variables` theme.
=> feat(Divider): add divider-horizontal-gutter variable

components/alert/index.en-US.md, components/alert/index.zh-CN.md, components/drawer/index.en-US.md, components/drawer/index.zh-CN.md
=> docs: update alert & drawer doc in closeIcon default value

site/src/vueDocs/i18n.zh-CN.md
=> docs: text error

package.json
```
$ yarn compile
> ant-design-vue@3.2.10 compile E:\Project\Vue\ant-design-vue
> node antd-tools/cli/run.js compile
antd-tools run compile
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module 'unified'
```
> 1. Basic thought of solution and other optional …
=> chore: add unified to devDependencies

components/input-number/index.tsx
fix #5853
在React那边也提交了[PR](https://github.com/ant-design/ant-design/pull/36922)
> 3. Does this PR …
=> fix(inputNumber): inputNumber size UI performance error

components/_util/props-util/index.js
`filterEmpty`不支持处理嵌套`Fragment`的情况。
可能会出现嵌套`Fragment`的情况：在封装组件时，有时候需要将父组件的`slots`透传给子组件，这时候`vue`就会处理成嵌套的`Fragment`的关系。所以`child.type === Fragment`时，应该递归处理`children`。
> 1. Does this PR affect …
=> feat(props-util): [filterEmpty] support nested fragment

components/form/index.en-US.md, components/form/index.zh-CN.md
=> docs(form): fix typo

antd-tools/generator-types/src/parser.ts
set the wrong default value by parse md table error.
- [x ] Bug fix
> 1. Does this PR affect user? …
=> fix generate web-types.json bug

components/config-provider/cssVariables.tsx
See my pull request to AntDegisn [#37304](https://github.com/ant-design/ant-design/pull/37304)
Issuse [#37303](https://github.com/ant-design/ant-design/issues/37303)
> 1. Does this PR affect …
=> fix: config provider theme active color not same in variable.less

components/table/style/index.less
=> fix: fix table container z-index

components/tag/index.tsx
>[Tag - Ant Design Vue (antdv.com)](https://www.antdv.com/components/tag)
>
>Fixed close icon plate shifting when import custom close icon
>
>![RUNOOB 图标](https://i.imgur.com/cqOZn3d.png)
=> Fixed close icon plate shifting when import custom close icon

components/table/Table.tsx
=> fix(Table): loading prop type definition

components/upload/index.en-US.md, components/upload/index.zh-CN.md
**Upload** components document update
Remove one of _openFileDialogOnClick_ props
上传组件的文档中openFileDialogOnClick 属性描述出现了两次，删掉了其中一个
=> docs（Upload）🍎remove one of openFileDialogOnClick props in docs

site/src/vueDocs/customize-theme.en-US.md, site/src/vueDocs/customize-theme.zh-CN.md
=> fix: Style variables describe error #6009

components/form/demo/customized-form-controls.vue
=> Site / document update

components/pagination/index.en-US.md, components/pagination/index.zh-CN.md
=> docs(pagination): docs update

components/tree-select/index.zh-CN.md
=> docs(tree-select): docs typos

components/select/index.en-US.md, components/select/index.zh-CN.md
=> docs(select): docs update

components/icon/style/index.less, components/icon/style/index.tsx, components/style.ts
=> refactor(icon): remove style dir

components/breadcrumb/Breadcrumb.tsx, components/descriptions/index.tsx, components/divider/index.tsx
=> fix: custom class

components/button/button.tsx
=> fix(button): link and text should not have wave

components/components.ts, components/segmented/__tests__/demo.test.js, components/segmented/__tests__/index.test.js, components/segmented/demo/basic.vue, components/segmented/demo/block.vue, components/segmented/demo/controlled.vue, components/segmented/demo/custom.vue, components/segmented/demo/disabled.vue, components/segmented/demo/dynamic.vue, components/segmented/demo/icon.vue, components/segmented/demo/index.vue, components/segmented/demo/size.vue, components/segmented/index.en-US.md, components/segmented/index.ts, components/segmented/index.zh-CN.md, components/segmented/src/index.ts, components/segmented/src/segmented.tsx, components/segmented/style/index.ts, components/theme/interface/components.ts
=> refactor: segmented

components/dropdown/dropdown.tsx
=> fix(dropdown): open invalid

components/vc-dropdown/Dropdown.tsx
=> fix(dropdown): fix close popup doesn't emit 'visibleChange' event 

components/slider/index.tsx
… for external use.
> 2. What will say …
=> fix: Export the types referenced in the Props of the Slider component for external use. fix #6338

components/menu/src/Divider.tsx
=> fix: dropdown divider disappear

components/date-picker/generatePicker/props.ts, components/date-picker/index.en-US.md, components/date-picker/index.zh-CN.md
> 1. dateRange props support rcustom function and update docs
> 2. keep in sync with react antd
> 3. https://github.com/ant-design/ant-design/issues/41257 …
=> feat[data-picker]: improve format types and docs

components/form/Form.tsx, components/form/FormItem.tsx
1、处理即将废弃的类型  ValidationRule 
2、更新 FormLabelAlign 以及 FormLayout 的类型提示
> 1. Does this PR affect …
=> Fix form type prompt

site/src/layouts/header/Menu.vue
=> feat(docs): version menu

.github/PULL_REQUEST_TEMPLATE/pr_cn.md, .github/PULL_REQUEST_TEMPLATE/pr_en.md
首先，感谢你的贡献！ 😄
pr文档：非新特性提交至main分支
=> docs(introduce): change pull request branch name in EN and CN introduce docs

components/_util/hooks/useMergedState.ts, components/upload/__tests__/__snapshots__/uploadlist.test.js.snap, components/upload/__tests__/requests.js, components/upload/__tests__/uploadlist.test.js
Reverts vueComponent/ant-design-vue#6402
=> Revert "fix: useMergedState is not updated in time"

components/date-picker/__tests__/QuarterPicker.test.js, components/date-picker/__tests__/RangePicker.test.js, components/date-picker/__tests__/__snapshots__/demo.test.js.snap, components/date-picker/generatePicker/generateRangePicker.tsx, components/vc-picker/generate/dayjs.ts
初始化week WeekPicker 时，存在 valueFormat 无法正常，显示日期，原因是 dayjs 目前无法处理 输入字符串包含周的格式，来解析日期。
https://day.js.org/docs/en/parse/string-format
dayjs 目前无法处理 输入字符串包含周的格式，来解析日期。
#6384 
> 3. GIF or …
=> fix(dayjs): cannot handle week and quarter String + Format

components/modal/ConfirmDialog.tsx
首先，感谢你的贡献！ 😄
Modal组件的国际化有误
> 2. 要解决的问题。
Modal组件的国际化有误
Modal组件的参数有误，修正即可
> 1. 英文描述
> 2. 中文描述（可选）
=> fix(Modal): fix modal locale

components/config-provider/context.ts
=> fix(defaultConfigProvider): add getPopupContainer

components/qrcode/__tests__/__snapshots__/demo.test.js.snap, components/qrcode/__tests__/index.test.js
=> test: add QRCode unit testing

components/badge/Badge.tsx
首先，感谢你的贡献！ 😄
[[English Template / 英文模板](./pr_en.md)]
> 2. 要解决的问题。
ref: #6432 
set props.count default valut to null
count: PropTypes.any.def(null),
> 1. 英文描述
fix(badge): badge props count default value error
> 2. 中文描述（可选）
修复badge props count 未设置默认值导致的dot样式未添加问题
=> fix(badge): badge props count default value error

components/date-picker/index.en-US.md, components/date-picker/index.zh-CN.md
首先，感谢你的贡献！ 😄
> 2. 要解决的问题。
#6449 
> 1. 英文描述
> 2. 中文描述（可选）
=> docs(DatePicker): update docs with How to modify start day of week

components/affix/index.en-US.md, components/affix/index.zh-CN.md, components/space/demo/index.vue
首先，感谢你的贡献！ 😄
> 2. 要解决的问题。
> 1. 英文描述
> 2. 中文描述（可选）
=> chore(docs): update docs

components/_util/cssinjs/transformers/legacyLogicalProperties.ts
配置 `transformers` 属性后 `calc()` 在转换中丢失空格，导致在chrome浏览器内失效
`calc(100% - 24px)`    ==>   `calc(100%-24)`
```html
// `transformers` 提供预处理功能将样式进行转换
<template>
<a-style-provider :transformers="[legacyLogicalPropertiesTransformer]">
<MyApp />
</a-style-provider>
</template>
<script lang="ts" setup>
import { legacyLogicalPropertiesTransformer } from 'ant-design-vue';
</script>
``` …
=> fix cssinjs compatibility

components/transfer/demo/tree-transfer.vue
=> fix(transfer): tree-transfer demo disabled style

components/vc-select/BaseSelect.tsx
=> fix(Select): fix polite span effect

components/form/FormItem.tsx
首先，感谢你的贡献！ 😄
使用表单校验时，发现表单校验会自动取值window.nam
> 2. 要解决的问题。
将取值从window改为从props上取值
> 1. 英文描述
> 2. 中文描述（可选）
=> fix(a-form):fixed use props.name instead window.name

components/anchor/Anchor.tsx, components/anchor/__tests__/__snapshots__/demo.test.js.snap, components/anchor/context.ts, components/anchor/demo/basic.vue, components/anchor/demo/horizontal.vue, components/anchor/demo/index.vue, components/anchor/index.en-US.md, components/anchor/index.zh-CN.md, components/anchor/style/index.ts
首先，感谢你的贡献！ 😄
增加 direction prop
> 2. 要解决的问题。
anchor 支持 横向展示
增加 横向展示 的样式，及其 行为逻辑
```vue
<template>
<div style="{padding: '20px';}">
<a-anchor
direction="horizontal"
:items="[
{
key: 'horizontally-part-1',
href: '#horizontally-part-1',
title: 'Part 1',
},
{
key: 'horizontally-part-2',
href: '#horizontally-part-2',
title: 'Part 2',
},
{
key: 'horizontally-part-3',
href: '#horizontally-part-3',
title: 'Part 3',
},
]"
/>
</div>
</template>
```
增加 使用 items 提示 devWarnning 提示
无
> 1. 英文描述
Add direction action
> 2. …
=> refactor(anchor): direction action

components/input-number/index.tsx
=> fix(input-number): fix the issuse of missing id when use in form

components/config-provider/index.tsx
=> fix(config-provider): fix ConfigProvider.config is not function close #6528

components/upload/index.en-US.md, components/upload/index.zh-CN.md
Modify the error description of the upload component document
修改了文档中的“手机设备如何选择相册或文件夹？”
修改了错误描述：`:accept="null"`
修改为正确描述：`:capture="null"`
=> Modify the error description of the upload component document

components/vc-tour/Mask.tsx
1. 修复vc-tour组件mask属性pointer-events: "auto"
=> fix tour-mask attrs pointer-events

components/tree-select/index.en-US.md, components/tree-select/index.zh-CN.md
=> docs(TreeSelect): update fieldNames docs

README-zh_CN.md, README.md
=> docs: add ant-design-vue nuxt module

components/vc-tour/Tour.tsx
=> fix(tour) target position

site/src/vueDocs/replace-date.en-US.md
replace-date.en-US.md 替换 => replace
=> docs(replace-date): replace-date.en-US.md 替换 => replace

components/qrcode/QRCode.tsx, components/qrcode/__tests__/__snapshots__/demo.test.js.snap, components/qrcode/demo/base.vue, components/qrcode/demo/customColor.vue, components/qrcode/demo/customSize.vue, components/qrcode/demo/customType.vue, components/qrcode/demo/download.vue, components/qrcode/demo/icon.vue, components/qrcode/demo/index.vue, components/qrcode/demo/popover.vue, components/qrcode/demo/status.vue, components/qrcode/index.en-US.md, components/qrcode/index.tsx, components/qrcode/index.zh-CN.md, components/qrcode/interface.ts
=> docs(QRCode): Synchronize QR code demonstration and add SVG

components/vc-image/src/Preview.tsx
=> fix(image): sensitivity of image scaling

components/vc-slick/inner-slider.jsx
=> fix(slick): changed autoplay slick invalid

components/page-header/__tests__/__snapshots__/demo.test.js.snap, components/page-header/demo/ghost.vue, components/page-header/style/index.ts
=> fix(PageHeader): ghost style

components/checkbox/Checkbox.tsx
=> fix(checkbox): change trigger form validation.

components/input/Input.tsx
=> fix(input): prefix prop has not been passed

site/src/layouts/header/index.vue
Reverts vueComponent/ant-design-vue#6799
=> Revert "docs: banner adjust light and dark mode"

site/src/layouts/header/SearchBox.vue, site/src/theme/static/common.less, site/src/theme/static/icons.less, site/src/theme/template/IconDisplay/CopyableIcon.vue, site/src/theme/template/IconDisplay/index.jsx
=> docs: add icon search input

components/image/__tests__/__snapshots__/demo.test.js.snap, components/vc-image/src/Image.tsx
=> fix: image height

components/table/style/index.ts
移除的 table 下的 tr 的圆角样式，以及上下 boder 的变化，和 ant-design 保持同步
=> style: remove table's tr rounded corner

components/pagination/style/index.tsx
=> style: fix pagination buttons transition style

site/src/theme/static/docsearch.less
=> site: improve algolia dropdown menu shadow effect

components/tabs/style/index.ts
=> fix(tabs): animated tabs style

components/tag/CheckableTag.tsx
=> fix(tag): checkable tag don't pass class props

components/drawer/demo/render-in-current.vue
=> fix(drawer): demo width overflow

components/badge/__tests__/__snapshots__/demo.test.js.snap, components/badge/style/index.ts
=> fix(badge): dot with processing status

site/src/layouts/index.vue, site/src/theme/static/page-nav.less, site/src/theme/static/responsive.less
=> site: improve footer & fix toc-affix

site/src/components/Contributors/index.vue
=> fix: add judgement condition for contributor list

site/src/components/DemoBox.vue, site/src/theme/static/common.less
=> site: add hide code btn in the bottom for code box

site/src/index.less, site/src/layouts/index.vue
=> site: mobile drawer menu trigger

components/tour/__tests__/index.test.js
Please add label "hacktoberfest-accepted" (without quotes) to this PR before merging.
Added testcases for Tour Component and improved code coverage.
=> Added testcases for Tour Component

typings/global.d.ts
=> chore: remove repeat type

components/checkbox/Checkbox.tsx
=> fix(checkbox): get disabled prop from parent

components/form/FormItem.tsx
=> fix(form-item): initialValue issue in resetField

components/drawer/index.tsx
=> fix(drawer): wrapper style pass to drawer content

components/pagination/index.en-US.md, components/pagination/index.zh-CN.md
update pageSizeOptions API's Type and Default
=> docs(pagination): fix pageSizeOptions API

components/vc-virtual-list/List.tsx, components/vc-virtual-list/ScrollBar.tsx
New feature please send pull request to feature branch, and rest to main branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!
[[中文版模板 / Chinese template](./pr_cn.md)]
> 2. …
=> fix(select): list scrollbar height and timing (#6987)

components/vc-select/BaseSelect.tsx
=> fix(select): Dropdown onVisibleChange invalid

components/space/index.tsx
=> fix: fix space duplicated key

components/checkbox/index.en-US.md, components/checkbox/index.zh-CN.md
`Checkbox Group`的`value`和`Checkbox`的`value`类型对应。
=> docs(checkbox): fix typo

components/upload/Upload.tsx
=> fix(upload): disabled prop apply order

site/src/layouts/Menu.vue, site/src/theme/static/common.less
=> site: menu show tag when front-matter has tag prop

.npmrc
使用 pnpm 的话，不会自动运行 pre/post 的 scripts。需要进行配置，具体详情可以查看 👉 [这里](https://pnpm.io/cli/run#enable-pre-post-scripts)
=> feat: enable pnpm run pre scripts

components/tree-select/demo/basic.vue, components/tree-select/demo/custom-tag-render.vue, components/tree-select/demo/highlight.vue, components/tree-select/demo/multiple.vue
修正 tree-select demo 存在选项值重复的问题
=> docs(tree-select): fix duplicate values in demo

components/vc-picker/Picker.tsx
=> fix DatePicker事件panelChange缺失

components/_util/vnode.ts
=> fix version3.x carousel rendering error in jsx

components/config-provider/index.en-US.md, components/config-provider/index.zh-CN.md
link #7106 
add wave setting docs
=> docs(config-provider): add wave setting

components/_util/wave/useWave.ts, components/config-provider/hooks/useConfigInject.ts
=> fix: useWave unref

components/vc-picker/RangePicker.tsx
=> fix(RangPicker): Incorrect display of prevIcon and nextIcon

components/watermark/index.tsx
Deeply monitor the changes in DOM tree properties of the entire watermark component
=> fix(watermark): modify dom properties to regenerate

components/menu/src/Menu.tsx
=> fix(menu): pass motion name  to collapseMotion

components/vc-trigger/Trigger.tsx
=> fix(dropdown):  unexpectedly hidden(#7246)

components/typography/index.zh-CN.md
https://www.antdv.com/components/typography-cn#editable 补充中文翻译
=> docs(typography): trigerType api supplement Chinese translation

components/divider/style/index.ts
https://www.antdv.com/components/divider-cn#components-divider-demo-customize-style
垂直虚线分割线没有显示出来
=> fix(divider): vertical dashed divider not show

components/locale/en_US.ts, components/locale/index.tsx, components/locale/zh_CN.ts, components/locale/zh_HK.ts, components/locale/zh_TW.ts, components/qrcode/__tests__/__snapshots__/demo.test.js.snap, components/qrcode/demo/status.vue, components/qrcode/index.en-US.md, components/qrcode/index.tsx, components/qrcode/index.zh-CN.md, components/qrcode/interface.ts, components/qrcode/style/index.ts
=> feat(QRCode): support scanned status

components/_util/hooks/_vueuse/_configurable.ts, components/_util/hooks/_vueuse/is.ts
Warning when building with Vite 5 /* #__PURE__*/ comment removed
=> fix: remove /* #__PURE__*/ comments

components/app/index.en-US.md, components/app/index.zh-CN.md
=> feat: 修复App 文档拼写错误

components/locale/ru_RU.ts
Add russian localization to tour, Qr code and form components ✨
=> Updated ru_RU localization

components/modal/index.en-US.md, components/modal/index.zh-CN.md
=> docs(Modal): add simplified descriptions

components/vc-pagination/Pagination.tsx
=> fix(Pagination): block default events for the enter key

antd-tools/generator-types/src/index.ts, antd-tools/generator-types/src/parser.ts, antd-tools/getTSCommonConfig.js, components/_util/getScroll.ts, components/_util/scrollTo.ts, components/_util/triggerEvent.ts, components/checkbox/Group.tsx, components/menu/src/Menu.tsx, components/menu/src/hooks/useItems.tsx, components/rate/util.ts, components/tree/demo/search.vue, components/vc-image/src/PreviewGroup.tsx, components/vc-picker/panels/TimePanel/TimeUnitColumn.tsx, components/vc-slider/src/common/createSlider.tsx, components/vc-slider/src/utils.ts, components/vc-tree-select/hooks/useDataEntities.ts, components/vc-tree/utils/treeUtil.ts, components/vc-util/Dom/css.ts, components/vc-util/isMobile.ts, package.json, site/src/components/vue-colorful/components/common/Interactive.tsx, site/src/components/vue-colorful/hooks/useStyleSheet.ts, site/src/layouts/header/Menu.vue
pageXOffset, pageYOffset => scrollX, scrollY
substr => substring
=> refactor: replement deprecated fields

components/float-button/interface.ts
close #7574 
| old | new |
| -- | -- |
| ![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/a043e1d2-3424-4585-841c-f74415487b9b) | ![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/5eb8c6d5-e038-49ca-8079-155c1fb71e43)  |
=> fix(FloatButton): type prompt error

components/form/FormItem.tsx
=> fix(FormItem): class name error

site/src/vueDocs/migration-v4.en-US.md, site/src/vueDocs/migration-v4.zh-CN.md
=> fix: upgrade document link direction error

components/_util/BaseInput.tsx
=> fix(Input): Chinese input is invalid when the modifier is lazy

components/date-picker/index.en-US.md, components/date-picker/index.zh-CN.md
dropdownClassName已废弃, 更换为popupClassName了, 文档中没有同步修改
=> docs(DatePicker): update deprecated API

components/vc-util/Dom/css.ts
=> fix[vc-util]: styleObjectToString filter invalid value

components/calendar/index.zh-CN.md, components/collapse/index.zh-CN.md, components/dropdown/index.zh-CN.md, components/input-number/index.zh-CN.md, components/modal/index.zh-CN.md, components/popconfirm/index.zh-CN.md, components/segmented/index.zh-CN.md, components/select/index.zh-CN.md, components/tabs/index.zh-CN.md, components/tooltip/index.zh-CN.md, components/upload/index.zh-CN.md
=> docs: unify the default value of none to -

components/tour/panelRender.tsx
Tour component TourStep custom button properties, no rendering of the passed parameter children
Tour 组件 TourStep 自定义按钮属性，没有渲染传入的参数 children
=> Fix: [修复自定义按钮无渲染]

components/slider/demo/event.vue
=> docs: event demo (#7699)

components/input-number/src/InputNumber.tsx
resolve [7723](https://github.com/vueComponent/ant-design-vue/issues/7723) [7268](https://github.com/vueComponent/ant-design-vue/issues/7268)
=> fix: Safari of input IME

components/vc-dialog/Content.tsx
=> fix(Dialog): aira error

components/input-number/style/index.tsx
| Before | After | 
| ------- | ------ |
| ![image](https://github.com/user-attachments/assets/71aff4ee-74f7-4b11-aa3a-35c59338885b) | ![image](https://github.com/user-attachments/assets/6aa9a800-2937-40a2-800a-6b9249330d69) |
close #7775
=> fix(InputNumber): disabled text color

components/input/index.en-US.md, components/input/index.zh-CN.md
修复官方文档showCount 类型为boolean  
实际可传入对象类型
=> docs(input): showCount type 文档

components/mentions/demo/placement.vue
=> docs(mentions): Spelling error in En title

components/card/Card.tsx, components/card/style/index.tsx
1. Card 组件支持 cssvar 特性，样式同步为最新 antd v5.26.1
=> feat[cssvar]: Card support cssvar

.github/workflows/codecov.yml, .github/workflows/test.yml
See https://github.com/actions/cache/discussions/1510 for more details.
=> Updated to actions/cache@v4 for GitHub workflows.
